import type { Destination, DestinationVibe } from '@/types/flash';

// Curated list of ~60 destinations with rich metadata
export const DESTINATIONS: Destination[] = [
  // Europe
  {
    id: 'paris',
    city: 'Paris',
    country: 'France',
    airportCode: 'CDG',
    region: 'europe',
    vibes: ['romance', 'culture', 'food', 'city', 'history'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 3500,
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Seine River cruises', 'Michelin dining'],
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    id: 'rome',
    city: 'Rome',
    country: 'Italy',
    airportCode: 'FCO',
    region: 'europe',
    vibes: ['history', 'culture', 'food', 'city'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 3000,
    highlights: ['Colosseum', 'Vatican City', 'Trevi Fountain', 'Italian cuisine'],
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    id: 'barcelona',
    city: 'Barcelona',
    country: 'Spain',
    airportCode: 'BCN',
    region: 'europe',
    vibes: ['beach', 'culture', 'nightlife', 'city', 'food'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 2800,
    highlights: ['La Sagrada Familia', 'Gothic Quarter', 'Barceloneta Beach', 'Tapas bars'],
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
    latitude: 41.3851,
    longitude: 2.1734,
  },
  {
    id: 'amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    airportCode: 'AMS',
    region: 'europe',
    vibes: ['culture', 'city', 'nightlife', 'history'],
    bestMonths: [4, 5, 6, 9],
    averageCost: 3200,
    highlights: ['Canal cruises', 'Van Gogh Museum', 'Anne Frank House', 'Bike tours'],
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800',
    latitude: 52.3676,
    longitude: 4.9041,
  },
  {
    id: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    airportCode: 'LIS',
    region: 'europe',
    vibes: ['culture', 'food', 'nightlife', 'city', 'beach'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 2200,
    highlights: ['Tram 28', 'Alfama district', 'Pastéis de Belém', 'Fado music'],
    imageUrl: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800',
    latitude: 38.7223,
    longitude: -9.1393,
  },
  {
    id: 'london',
    city: 'London',
    country: 'United Kingdom',
    airportCode: 'LHR',
    region: 'europe',
    vibes: ['culture', 'city', 'history', 'nightlife', 'food'],
    bestMonths: [5, 6, 7, 9],
    averageCost: 4000,
    highlights: ['Big Ben', 'Tower of London', 'British Museum', 'West End shows'],
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 'santorini',
    city: 'Santorini',
    country: 'Greece',
    airportCode: 'JTR',
    region: 'europe',
    vibes: ['romance', 'beach', 'relaxation', 'luxury'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 4500,
    highlights: ['Oia sunsets', 'Blue-domed churches', 'Wine tasting', 'Caldera views'],
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
    latitude: 36.3932,
    longitude: 25.4615,
  },
  {
    id: 'prague',
    city: 'Prague',
    country: 'Czech Republic',
    airportCode: 'PRG',
    region: 'europe',
    vibes: ['history', 'culture', 'city', 'nightlife'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 2000,
    highlights: ['Charles Bridge', 'Prague Castle', 'Old Town Square', 'Beer culture'],
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800',
    latitude: 50.0755,
    longitude: 14.4378,
  },
  {
    id: 'dubrovnik',
    city: 'Dubrovnik',
    country: 'Croatia',
    airportCode: 'DBV',
    region: 'europe',
    vibes: ['history', 'beach', 'culture', 'romance'],
    bestMonths: [5, 6, 9],
    averageCost: 2800,
    highlights: ['Old Town walls', 'Game of Thrones sites', 'Adriatic beaches', 'Kayaking'],
    imageUrl: 'https://images.unsplash.com/photo-1555990538-1e6c2f3d8a2e?w=800',
    latitude: 42.6507,
    longitude: 18.0944,
  },
  {
    id: 'reykjavik',
    city: 'Reykjavik',
    country: 'Iceland',
    airportCode: 'KEF',
    region: 'europe',
    vibes: ['adventure', 'nature', 'relaxation'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    averageCost: 5000,
    highlights: ['Northern Lights', 'Blue Lagoon', 'Golden Circle', 'Glacier hiking'],
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800',
    latitude: 64.1466,
    longitude: -21.9426,
  },
  {
    id: 'vienna',
    city: 'Vienna',
    country: 'Austria',
    airportCode: 'VIE',
    region: 'europe',
    vibes: ['culture', 'history', 'food', 'city'],
    bestMonths: [4, 5, 9, 10, 12],
    averageCost: 3000,
    highlights: ['Schönbrunn Palace', 'Vienna Opera', 'Coffee houses', 'Christmas markets'],
    imageUrl: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800',
    latitude: 48.2082,
    longitude: 16.3738,
  },
  {
    id: 'swiss-alps',
    city: 'Interlaken',
    country: 'Switzerland',
    airportCode: 'ZRH',
    region: 'europe',
    vibes: ['adventure', 'nature', 'relaxation', 'luxury'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    averageCost: 5500,
    highlights: ['Jungfrau', 'Paragliding', 'Swiss villages', 'Mountain railways'],
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    latitude: 46.6863,
    longitude: 7.8632,
  },
  {
    id: 'amalfi',
    city: 'Amalfi Coast',
    country: 'Italy',
    airportCode: 'NAP',
    region: 'europe',
    vibes: ['romance', 'beach', 'food', 'luxury', 'relaxation'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 4500,
    highlights: ['Positano', 'Ravello gardens', 'Limoncello', 'Coastal drives'],
    imageUrl: 'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=800',
    latitude: 40.6333,
    longitude: 14.6029,
  },

  // Asia
  {
    id: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    airportCode: 'HND',
    region: 'asia',
    vibes: ['culture', 'city', 'food', 'nightlife'],
    bestMonths: [3, 4, 10, 11],
    averageCost: 4000,
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Sushi Dai', 'Cherry blossoms'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    latitude: 35.6762,
    longitude: 139.6503,
  },
  {
    id: 'bali',
    city: 'Bali',
    country: 'Indonesia',
    airportCode: 'DPS',
    region: 'asia',
    vibes: ['beach', 'relaxation', 'culture', 'nature', 'family'],
    bestMonths: [4, 5, 6, 7, 8, 9],
    averageCost: 2500,
    highlights: ['Ubud rice terraces', 'Uluwatu Temple', 'Beach clubs', 'Yoga retreats'],
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    latitude: -8.4095,
    longitude: 115.1889,
  },
  {
    id: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    airportCode: 'BKK',
    region: 'asia',
    vibes: ['culture', 'food', 'nightlife', 'city'],
    bestMonths: [11, 12, 1, 2],
    averageCost: 2000,
    highlights: ['Grand Palace', 'Street food', 'Floating markets', 'Rooftop bars'],
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    latitude: 13.7563,
    longitude: 100.5018,
  },
  {
    id: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    airportCode: 'SIN',
    region: 'asia',
    vibes: ['city', 'food', 'family', 'luxury'],
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    averageCost: 4000,
    highlights: ['Gardens by the Bay', 'Marina Bay Sands', 'Hawker centers', 'Sentosa'],
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
    latitude: 1.3521,
    longitude: 103.8198,
  },
  {
    id: 'kyoto',
    city: 'Kyoto',
    country: 'Japan',
    airportCode: 'KIX',
    region: 'asia',
    vibes: ['culture', 'history', 'nature', 'relaxation'],
    bestMonths: [3, 4, 10, 11],
    averageCost: 3800,
    highlights: ['Fushimi Inari', 'Geisha district', 'Bamboo grove', 'Tea ceremonies'],
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    latitude: 35.0116,
    longitude: 135.7681,
  },
  {
    id: 'vietnam',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    airportCode: 'SGN',
    region: 'asia',
    vibes: ['culture', 'food', 'history', 'adventure'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 1800,
    highlights: ['Cu Chi Tunnels', 'Street food tours', 'Mekong Delta', 'War museums'],
    imageUrl: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800',
    latitude: 10.8231,
    longitude: 106.6297,
  },
  {
    id: 'maldives',
    city: 'Maldives',
    country: 'Maldives',
    airportCode: 'MLE',
    region: 'asia',
    vibes: ['beach', 'romance', 'luxury', 'relaxation'],
    bestMonths: [1, 2, 3, 4, 11, 12],
    averageCost: 8000,
    highlights: ['Overwater bungalows', 'Snorkeling', 'Private islands', 'Sunset cruises'],
    imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    latitude: 3.2028,
    longitude: 73.2207,
  },
  {
    id: 'hong-kong',
    city: 'Hong Kong',
    country: 'Hong Kong',
    airportCode: 'HKG',
    region: 'asia',
    vibes: ['city', 'food', 'nightlife', 'culture'],
    bestMonths: [10, 11, 12],
    averageCost: 3500,
    highlights: ['Victoria Peak', 'Dim sum', 'Star Ferry', 'Night markets'],
    imageUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800',
    latitude: 22.3193,
    longitude: 114.1694,
  },
  {
    id: 'sri-lanka',
    city: 'Colombo',
    country: 'Sri Lanka',
    airportCode: 'CMB',
    region: 'asia',
    vibes: ['nature', 'culture', 'beach', 'adventure', 'history'],
    bestMonths: [1, 2, 3, 7, 8],
    averageCost: 2000,
    highlights: ['Sigiriya Rock', 'Tea plantations', 'Safari', 'Ancient temples'],
    imageUrl: 'https://images.unsplash.com/photo-1586613836474-85a0a54b66a5?w=800',
    latitude: 6.9271,
    longitude: 79.8612,
  },

  // Americas
  {
    id: 'new-york',
    city: 'New York',
    country: 'United States',
    airportCode: 'JFK',
    region: 'americas',
    vibes: ['city', 'culture', 'food', 'nightlife'],
    bestMonths: [4, 5, 9, 10, 12],
    averageCost: 4500,
    highlights: ['Times Square', 'Central Park', 'Broadway', 'Statue of Liberty'],
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    latitude: 40.7128,
    longitude: -74.0060,
  },
  {
    id: 'cancun',
    city: 'Cancun',
    country: 'Mexico',
    airportCode: 'CUN',
    region: 'americas',
    vibes: ['beach', 'nightlife', 'family', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2500,
    highlights: ['Beach resorts', 'Chichen Itza', 'Cenotes', 'Underwater museum'],
    imageUrl: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800',
    latitude: 21.1619,
    longitude: -86.8515,
  },
  {
    id: 'costa-rica',
    city: 'San Jose',
    country: 'Costa Rica',
    airportCode: 'SJO',
    region: 'americas',
    vibes: ['adventure', 'nature', 'beach', 'family'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3000,
    highlights: ['Cloud forests', 'Volcano hiking', 'Zip lining', 'Wildlife'],
    imageUrl: 'https://images.unsplash.com/photo-1518259102261-b40117eabbc9?w=800',
    latitude: 9.9281,
    longitude: -84.0907,
  },
  {
    id: 'miami',
    city: 'Miami',
    country: 'United States',
    airportCode: 'MIA',
    region: 'americas',
    vibes: ['beach', 'nightlife', 'city', 'food'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3500,
    highlights: ['South Beach', 'Art Deco district', 'Cuban food', 'Everglades'],
    imageUrl: 'https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?w=800',
    latitude: 25.7617,
    longitude: -80.1918,
  },
  {
    id: 'peru',
    city: 'Cusco',
    country: 'Peru',
    airportCode: 'CUZ',
    region: 'americas',
    vibes: ['adventure', 'history', 'culture', 'nature'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 2800,
    highlights: ['Machu Picchu', 'Sacred Valley', 'Rainbow Mountain', 'Inca Trail'],
    imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
    latitude: -13.5319,
    longitude: -71.9675,
  },
  {
    id: 'rio',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    airportCode: 'GIG',
    region: 'americas',
    vibes: ['beach', 'nightlife', 'culture', 'adventure'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Christ the Redeemer', 'Copacabana', 'Sugarloaf', 'Samba'],
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
    latitude: -22.9068,
    longitude: -43.1729,
  },
  {
    id: 'buenos-aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    airportCode: 'EZE',
    region: 'americas',
    vibes: ['culture', 'food', 'nightlife', 'city'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2500,
    highlights: ['Tango shows', 'Steak houses', 'La Boca', 'Recoleta Cemetery'],
    imageUrl: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800',
    latitude: -34.6037,
    longitude: -58.3816,
  },
  {
    id: 'hawaii',
    city: 'Honolulu',
    country: 'United States',
    airportCode: 'HNL',
    region: 'americas',
    vibes: ['beach', 'nature', 'relaxation', 'family', 'adventure'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 5000,
    highlights: ['Waikiki Beach', 'Diamond Head', 'Pearl Harbor', 'Luaus'],
    imageUrl: 'https://images.unsplash.com/photo-1507876466758-bc54f384809c?w=800',
    latitude: 21.3069,
    longitude: -157.8583,
  },

  // Caribbean
  {
    id: 'jamaica',
    city: 'Montego Bay',
    country: 'Jamaica',
    airportCode: 'MBJ',
    region: 'caribbean',
    vibes: ['beach', 'relaxation', 'nightlife', 'culture'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3000,
    highlights: ['All-inclusive resorts', 'Dunn\'s River Falls', 'Reggae', 'Jerk cuisine'],
    imageUrl: 'https://images.unsplash.com/photo-1580237541049-2d715a09486e?w=800',
    latitude: 18.4762,
    longitude: -77.8939,
  },
  {
    id: 'bahamas',
    city: 'Nassau',
    country: 'Bahamas',
    airportCode: 'NAS',
    region: 'caribbean',
    vibes: ['beach', 'luxury', 'family', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 4500,
    highlights: ['Atlantis Resort', 'Swimming pigs', 'Clear waters', 'Island hopping'],
    imageUrl: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800',
    latitude: 25.0343,
    longitude: -77.3963,
  },
  {
    id: 'aruba',
    city: 'Oranjestad',
    country: 'Aruba',
    airportCode: 'AUA',
    region: 'caribbean',
    vibes: ['beach', 'relaxation', 'romance', 'adventure'],
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    averageCost: 3500,
    highlights: ['Eagle Beach', 'Natural bridges', 'Flamingos', 'Water sports'],
    imageUrl: 'https://images.unsplash.com/photo-1548963670-aaaa8f73a5e3?w=800',
    latitude: 12.5211,
    longitude: -69.9683,
  },
  {
    id: 'st-lucia',
    city: 'Castries',
    country: 'Saint Lucia',
    airportCode: 'UVF',
    region: 'caribbean',
    vibes: ['romance', 'beach', 'nature', 'luxury', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4, 5],
    averageCost: 4500,
    highlights: ['Pitons', 'Rainforest', 'Volcanic beaches', 'Luxury resorts'],
    imageUrl: 'https://images.unsplash.com/photo-1499002238440-d264f5e7e7fe?w=800',
    latitude: 14.0101,
    longitude: -60.9870,
  },

  // Middle East
  {
    id: 'dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    airportCode: 'DXB',
    region: 'middle_east',
    vibes: ['luxury', 'city', 'beach', 'family'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 5000,
    highlights: ['Burj Khalifa', 'Desert safari', 'Dubai Mall', 'Palm Jumeirah'],
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
    latitude: 25.2048,
    longitude: 55.2708,
  },
  {
    id: 'jordan',
    city: 'Amman',
    country: 'Jordan',
    airportCode: 'AMM',
    region: 'middle_east',
    vibes: ['history', 'adventure', 'culture'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2500,
    highlights: ['Petra', 'Dead Sea', 'Wadi Rum', 'Roman ruins'],
    imageUrl: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=800',
    latitude: 31.9454,
    longitude: 35.9284,
  },
  {
    id: 'israel',
    city: 'Tel Aviv',
    country: 'Israel',
    airportCode: 'TLV',
    region: 'middle_east',
    vibes: ['beach', 'culture', 'food', 'nightlife', 'history'],
    bestMonths: [4, 5, 10, 11],
    averageCost: 3500,
    highlights: ['Old Jaffa', 'Beaches', 'Bauhaus architecture', 'Jerusalem day trips'],
    imageUrl: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=800',
    latitude: 32.0853,
    longitude: 34.7818,
  },
  {
    id: 'oman',
    city: 'Muscat',
    country: 'Oman',
    airportCode: 'MCT',
    region: 'middle_east',
    vibes: ['culture', 'adventure', 'beach', 'history'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Grand Mosque', 'Wadis', 'Desert camping', 'Coastal fjords'],
    imageUrl: 'https://images.unsplash.com/photo-1559183618-0bb2f62d7c51?w=800',
    latitude: 23.5880,
    longitude: 58.3829,
  },

  // Africa
  {
    id: 'cape-town',
    city: 'Cape Town',
    country: 'South Africa',
    airportCode: 'CPT',
    region: 'africa',
    vibes: ['adventure', 'nature', 'food', 'beach', 'culture'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Table Mountain', 'Wine country', 'Cape of Good Hope', 'Penguins'],
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800',
    latitude: -33.9249,
    longitude: 18.4241,
  },
  {
    id: 'morocco',
    city: 'Marrakech',
    country: 'Morocco',
    airportCode: 'RAK',
    region: 'africa',
    vibes: ['culture', 'food', 'adventure', 'history'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2000,
    highlights: ['Medina', 'Souks', 'Riads', 'Sahara excursions'],
    imageUrl: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800',
    latitude: 31.6295,
    longitude: -7.9811,
  },
  {
    id: 'tanzania',
    city: 'Arusha',
    country: 'Tanzania',
    airportCode: 'JRO',
    region: 'africa',
    vibes: ['adventure', 'nature', 'family'],
    bestMonths: [6, 7, 8, 9, 1, 2],
    averageCost: 6000,
    highlights: ['Serengeti safari', 'Ngorongoro Crater', 'Zanzibar', 'Kilimanjaro'],
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    latitude: -3.3869,
    longitude: 36.6830,
  },
  {
    id: 'egypt',
    city: 'Cairo',
    country: 'Egypt',
    airportCode: 'CAI',
    region: 'africa',
    vibes: ['history', 'culture', 'adventure'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 2500,
    highlights: ['Pyramids of Giza', 'Nile cruise', 'Luxor temples', 'Abu Simbel'],
    imageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800',
    latitude: 30.0444,
    longitude: 31.2357,
  },
  {
    id: 'mauritius',
    city: 'Port Louis',
    country: 'Mauritius',
    airportCode: 'MRU',
    region: 'africa',
    vibes: ['beach', 'romance', 'luxury', 'relaxation', 'nature'],
    bestMonths: [5, 6, 7, 8, 9, 10, 11],
    averageCost: 4500,
    highlights: ['Underwater waterfall', 'Beaches', 'Resorts', 'Seven Colored Earths'],
    imageUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800',
    latitude: -20.1609,
    longitude: 57.5012,
  },

  // Oceania
  {
    id: 'sydney',
    city: 'Sydney',
    country: 'Australia',
    airportCode: 'SYD',
    region: 'oceania',
    vibes: ['city', 'beach', 'culture', 'food', 'nature'],
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    averageCost: 5000,
    highlights: ['Opera House', 'Harbour Bridge', 'Bondi Beach', 'Blue Mountains'],
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
    latitude: -33.8688,
    longitude: 151.2093,
  },
  {
    id: 'new-zealand',
    city: 'Queenstown',
    country: 'New Zealand',
    airportCode: 'ZQN',
    region: 'oceania',
    vibes: ['adventure', 'nature', 'relaxation'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 4500,
    highlights: ['Bungee jumping', 'Milford Sound', 'Lord of the Rings', 'Glaciers'],
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    latitude: -45.0312,
    longitude: 168.6626,
  },
  {
    id: 'fiji',
    city: 'Nadi',
    country: 'Fiji',
    airportCode: 'NAN',
    region: 'oceania',
    vibes: ['beach', 'relaxation', 'romance', 'family', 'adventure'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 4000,
    highlights: ['Island resorts', 'Snorkeling', 'Village visits', 'Water sports'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: -17.7765,
    longitude: 177.4356,
  },
  {
    id: 'tahiti',
    city: 'Papeete',
    country: 'French Polynesia',
    airportCode: 'PPT',
    region: 'oceania',
    vibes: ['beach', 'romance', 'luxury', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 8000,
    highlights: ['Bora Bora', 'Overwater bungalows', 'Diving', 'Lagoons'],
    imageUrl: 'https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=800',
    latitude: -17.6509,
    longitude: -149.4260,
  },
];

// Helper functions
export function getDestinationById(id: string): Destination | undefined {
  return DESTINATIONS.find(d => d.id === id);
}

export function getDestinationsByRegion(region: string): Destination[] {
  return DESTINATIONS.filter(d => d.region === region);
}

export function getDestinationsByVibe(vibe: DestinationVibe): Destination[] {
  return DESTINATIONS.filter(d => d.vibes.includes(vibe));
}

export function getDestinationsForMonth(month: number): Destination[] {
  return DESTINATIONS.filter(d => d.bestMonths.includes(month));
}

export function searchDestinations(query: string): Destination[] {
  const lowerQuery = query.toLowerCase();
  return DESTINATIONS.filter(
    d =>
      d.city.toLowerCase().includes(lowerQuery) ||
      d.country.toLowerCase().includes(lowerQuery) ||
      d.airportCode.toLowerCase().includes(lowerQuery) ||
      d.vibes.some(v => v.includes(lowerQuery))
  );
}
