import type { Destination, DestinationVibe } from '@/types/flash';

// Curated list of 250+ destinations with rich metadata
export const DESTINATIONS: Destination[] = [
  // ============================================
  // EUROPE (~50 destinations)
  // ============================================
  {
    id: 'paris',
    city: 'Paris',
    country: 'France',
    airportCode: 'CDG',
    region: 'europe',
    vibes: ['romance', 'culture', 'food', 'city', 'history'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 3500,
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Seine River cruises', 'Michelin dining'],
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    id: 'rome',
    city: 'Rome',
    country: 'Italy',
    airportCode: 'FCO',
    region: 'europe',
    vibes: ['history', 'culture', 'food', 'city'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 3000,
    highlights: ['Colosseum', 'Vatican City', 'Trevi Fountain', 'Italian cuisine'],
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    latitude: 41.9028,
    longitude: 12.4964,
  },
  {
    id: 'barcelona',
    city: 'Barcelona',
    country: 'Spain',
    airportCode: 'BCN',
    region: 'europe',
    vibes: ['beach', 'culture', 'nightlife', 'city', 'food'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 2800,
    highlights: ['La Sagrada Familia', 'Gothic Quarter', 'Barceloneta Beach', 'Tapas bars'],
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
    latitude: 41.3851,
    longitude: 2.1734,
  },
  {
    id: 'amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    airportCode: 'AMS',
    region: 'europe',
    vibes: ['culture', 'city', 'nightlife', 'history'],
    bestMonths: [4, 5, 6, 9],
    averageCost: 3200,
    highlights: ['Canal cruises', 'Van Gogh Museum', 'Anne Frank House', 'Bike tours'],
    imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800',
    latitude: 52.3676,
    longitude: 4.9041,
  },
  {
    id: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    airportCode: 'LIS',
    region: 'europe',
    vibes: ['culture', 'food', 'nightlife', 'city', 'beach'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 2200,
    highlights: ['Tram 28', 'Alfama district', 'Pastéis de Belém', 'Fado music'],
    imageUrl: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=800',
    latitude: 38.7223,
    longitude: -9.1393,
  },
  {
    id: 'london',
    city: 'London',
    country: 'United Kingdom',
    airportCode: 'LHR',
    region: 'europe',
    vibes: ['culture', 'city', 'history', 'nightlife', 'food'],
    bestMonths: [5, 6, 7, 9],
    averageCost: 4000,
    highlights: ['Big Ben', 'Tower of London', 'British Museum', 'West End shows'],
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 'santorini',
    city: 'Santorini',
    country: 'Greece',
    airportCode: 'JTR',
    region: 'europe',
    vibes: ['romance', 'beach', 'relaxation', 'luxury'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 4500,
    highlights: ['Oia sunsets', 'Blue-domed churches', 'Wine tasting', 'Caldera views'],
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800',
    latitude: 36.3932,
    longitude: 25.4615,
  },
  {
    id: 'prague',
    city: 'Prague',
    country: 'Czech Republic',
    airportCode: 'PRG',
    region: 'europe',
    vibes: ['history', 'culture', 'city', 'nightlife'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 2000,
    highlights: ['Charles Bridge', 'Prague Castle', 'Old Town Square', 'Beer culture'],
    imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800',
    latitude: 50.0755,
    longitude: 14.4378,
  },
  {
    id: 'dubrovnik',
    city: 'Dubrovnik',
    country: 'Croatia',
    airportCode: 'DBV',
    region: 'europe',
    vibes: ['history', 'beach', 'culture', 'romance'],
    bestMonths: [5, 6, 9],
    averageCost: 2800,
    highlights: ['Old Town walls', 'Game of Thrones sites', 'Adriatic beaches', 'Kayaking'],
    imageUrl: 'https://images.unsplash.com/photo-1555990538-1e6c2f3d8a2e?w=800',
    latitude: 42.6507,
    longitude: 18.0944,
  },
  {
    id: 'reykjavik',
    city: 'Reykjavik',
    country: 'Iceland',
    airportCode: 'KEF',
    region: 'europe',
    vibes: ['adventure', 'nature', 'relaxation'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    averageCost: 5000,
    highlights: ['Northern Lights', 'Blue Lagoon', 'Golden Circle', 'Glacier hiking'],
    imageUrl: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?w=800',
    latitude: 64.1466,
    longitude: -21.9426,
  },
  {
    id: 'vienna',
    city: 'Vienna',
    country: 'Austria',
    airportCode: 'VIE',
    region: 'europe',
    vibes: ['culture', 'history', 'food', 'city'],
    bestMonths: [4, 5, 9, 10, 12],
    averageCost: 3000,
    highlights: ['Schönbrunn Palace', 'Vienna Opera', 'Coffee houses', 'Christmas markets'],
    imageUrl: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800',
    latitude: 48.2082,
    longitude: 16.3738,
  },
  {
    id: 'swiss-alps',
    city: 'Interlaken',
    country: 'Switzerland',
    airportCode: 'ZRH',
    region: 'europe',
    vibes: ['adventure', 'nature', 'relaxation', 'luxury'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    averageCost: 5500,
    highlights: ['Jungfrau', 'Paragliding', 'Swiss villages', 'Mountain railways'],
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    latitude: 46.6863,
    longitude: 7.8632,
  },
  {
    id: 'amalfi',
    city: 'Amalfi Coast',
    country: 'Italy',
    airportCode: 'NAP',
    region: 'europe',
    vibes: ['romance', 'beach', 'food', 'luxury', 'relaxation'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 4500,
    highlights: ['Positano', 'Ravello gardens', 'Limoncello', 'Coastal drives'],
    imageUrl: 'https://images.unsplash.com/photo-1533587851505-d119e13fa0d7?w=800',
    latitude: 40.6333,
    longitude: 14.6029,
  },
  {
    id: 'florence',
    city: 'Florence',
    country: 'Italy',
    airportCode: 'FLR',
    region: 'europe',
    vibes: ['culture', 'history', 'food', 'city'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 3200,
    highlights: ['Uffizi Gallery', 'Duomo', 'Ponte Vecchio', 'Tuscan wine'],
    imageUrl: 'https://images.unsplash.com/photo-1543429258-c5ca3d4d7f1e?w=800',
    latitude: 43.7696,
    longitude: 11.2558,
  },
  {
    id: 'venice',
    city: 'Venice',
    country: 'Italy',
    airportCode: 'VCE',
    region: 'europe',
    vibes: ['romance', 'culture', 'history', 'city'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 3800,
    highlights: ['Grand Canal', 'St. Mark\'s Square', 'Gondola rides', 'Murano glass'],
    imageUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800',
    latitude: 45.4408,
    longitude: 12.3155,
  },
  {
    id: 'milan',
    city: 'Milan',
    country: 'Italy',
    airportCode: 'MXP',
    region: 'europe',
    vibes: ['city', 'culture', 'food', 'luxury'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 3500,
    highlights: ['Duomo di Milano', 'Last Supper', 'Fashion district', 'La Scala'],
    imageUrl: 'https://images.unsplash.com/photo-1520440229-6469a149ac59?w=800',
    latitude: 45.4642,
    longitude: 9.1900,
  },
  {
    id: 'madrid',
    city: 'Madrid',
    country: 'Spain',
    airportCode: 'MAD',
    region: 'europe',
    vibes: ['culture', 'food', 'nightlife', 'city', 'history'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 2800,
    highlights: ['Prado Museum', 'Retiro Park', 'Tapas bars', 'Flamenco shows'],
    imageUrl: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800',
    latitude: 40.4168,
    longitude: -3.7038,
  },
  {
    id: 'seville',
    city: 'Seville',
    country: 'Spain',
    airportCode: 'SVQ',
    region: 'europe',
    vibes: ['culture', 'history', 'food', 'nightlife'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2200,
    highlights: ['Alcázar', 'Flamenco', 'Plaza de España', 'Tapas culture'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    latitude: 37.3891,
    longitude: -5.9845,
  },
  {
    id: 'munich',
    city: 'Munich',
    country: 'Germany',
    airportCode: 'MUC',
    region: 'europe',
    vibes: ['culture', 'city', 'food', 'history'],
    bestMonths: [5, 6, 7, 9, 10],
    averageCost: 3000,
    highlights: ['Marienplatz', 'Beer halls', 'Oktoberfest', 'BMW Museum'],
    imageUrl: 'https://images.unsplash.com/photo-1595867818082-083862f3d630?w=800',
    latitude: 48.1351,
    longitude: 11.5820,
  },
  {
    id: 'berlin',
    city: 'Berlin',
    country: 'Germany',
    airportCode: 'BER',
    region: 'europe',
    vibes: ['culture', 'nightlife', 'history', 'city'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 2500,
    highlights: ['Brandenburg Gate', 'Berlin Wall', 'Museum Island', 'Techno clubs'],
    imageUrl: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800',
    latitude: 52.5200,
    longitude: 13.4050,
  },
  {
    id: 'brussels',
    city: 'Brussels',
    country: 'Belgium',
    airportCode: 'BRU',
    region: 'europe',
    vibes: ['culture', 'food', 'city', 'history'],
    bestMonths: [4, 5, 6, 9],
    averageCost: 2800,
    highlights: ['Grand Place', 'Belgian chocolate', 'Waffles', 'Art Nouveau'],
    imageUrl: 'https://images.unsplash.com/photo-1559113513-d5e09c78b9dd?w=800',
    latitude: 50.8503,
    longitude: 4.3517,
  },
  {
    id: 'copenhagen',
    city: 'Copenhagen',
    country: 'Denmark',
    airportCode: 'CPH',
    region: 'europe',
    vibes: ['culture', 'food', 'city', 'family'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 3800,
    highlights: ['Tivoli Gardens', 'Nyhavn', 'Little Mermaid', 'New Nordic cuisine'],
    imageUrl: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800',
    latitude: 55.6761,
    longitude: 12.5683,
  },
  {
    id: 'stockholm',
    city: 'Stockholm',
    country: 'Sweden',
    airportCode: 'ARN',
    region: 'europe',
    vibes: ['culture', 'city', 'nature', 'history'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 3500,
    highlights: ['Gamla Stan', 'Vasa Museum', 'Archipelago', 'ABBA Museum'],
    imageUrl: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800',
    latitude: 59.3293,
    longitude: 18.0686,
  },
  {
    id: 'oslo',
    city: 'Oslo',
    country: 'Norway',
    airportCode: 'OSL',
    region: 'europe',
    vibes: ['nature', 'culture', 'city'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 4200,
    highlights: ['Viking Ship Museum', 'Fjords', 'Opera House', 'Vigeland Park'],
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    latitude: 59.9139,
    longitude: 10.7522,
  },
  {
    id: 'helsinki',
    city: 'Helsinki',
    country: 'Finland',
    airportCode: 'HEL',
    region: 'europe',
    vibes: ['culture', 'nature', 'city', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 3200,
    highlights: ['Suomenlinna', 'Saunas', 'Design District', 'Market Square'],
    imageUrl: 'https://images.unsplash.com/photo-1538332576228-eb5b4c4de6f5?w=800',
    latitude: 60.1699,
    longitude: 24.9384,
  },
  {
    id: 'edinburgh',
    city: 'Edinburgh',
    country: 'United Kingdom',
    airportCode: 'EDI',
    region: 'europe',
    vibes: ['history', 'culture', 'city', 'nightlife'],
    bestMonths: [5, 6, 7, 8],
    averageCost: 3000,
    highlights: ['Edinburgh Castle', 'Royal Mile', 'Arthur\'s Seat', 'Whisky tours'],
    imageUrl: 'https://images.unsplash.com/photo-1506377585622-bedcbb5f8873?w=800',
    latitude: 55.9533,
    longitude: -3.1883,
  },
  {
    id: 'dublin',
    city: 'Dublin',
    country: 'Ireland',
    airportCode: 'DUB',
    region: 'europe',
    vibes: ['culture', 'nightlife', 'history', 'city'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 3200,
    highlights: ['Temple Bar', 'Guinness Storehouse', 'Trinity College', 'Irish pubs'],
    imageUrl: 'https://images.unsplash.com/photo-1549918864-48ac978761a4?w=800',
    latitude: 53.3498,
    longitude: -6.2603,
  },
  {
    id: 'budapest',
    city: 'Budapest',
    country: 'Hungary',
    airportCode: 'BUD',
    region: 'europe',
    vibes: ['culture', 'nightlife', 'history', 'relaxation'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 1800,
    highlights: ['Thermal baths', 'Parliament', 'Ruin bars', 'Danube views'],
    imageUrl: 'https://images.unsplash.com/photo-1541343672885-9be56236302a?w=800',
    latitude: 47.4979,
    longitude: 19.0402,
  },
  {
    id: 'krakow',
    city: 'Krakow',
    country: 'Poland',
    airportCode: 'KRK',
    region: 'europe',
    vibes: ['history', 'culture', 'city', 'nightlife'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 1500,
    highlights: ['Wawel Castle', 'Main Square', 'Jewish Quarter', 'Salt mines'],
    imageUrl: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=800',
    latitude: 50.0647,
    longitude: 19.9450,
  },
  {
    id: 'athens',
    city: 'Athens',
    country: 'Greece',
    airportCode: 'ATH',
    region: 'europe',
    vibes: ['history', 'culture', 'food', 'city'],
    bestMonths: [4, 5, 9, 10, 11],
    averageCost: 2200,
    highlights: ['Acropolis', 'Plaka', 'Greek cuisine', 'Ancient Agora'],
    imageUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800',
    latitude: 37.9838,
    longitude: 23.7275,
  },
  {
    id: 'mykonos',
    city: 'Mykonos',
    country: 'Greece',
    airportCode: 'JMK',
    region: 'europe',
    vibes: ['beach', 'nightlife', 'luxury', 'romance'],
    bestMonths: [6, 7, 8, 9],
    averageCost: 5000,
    highlights: ['Windmills', 'Beach clubs', 'Little Venice', 'Nightlife'],
    imageUrl: 'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800',
    latitude: 37.4467,
    longitude: 25.3289,
  },
  {
    id: 'crete',
    city: 'Heraklion',
    country: 'Greece',
    airportCode: 'HER',
    region: 'europe',
    vibes: ['beach', 'history', 'nature', 'food'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 2500,
    highlights: ['Knossos Palace', 'Samaria Gorge', 'Beaches', 'Cretan cuisine'],
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-3f8d9c34a4d2?w=800',
    latitude: 35.2401,
    longitude: 24.8093,
  },
  {
    id: 'porto',
    city: 'Porto',
    country: 'Portugal',
    airportCode: 'OPO',
    region: 'europe',
    vibes: ['culture', 'food', 'city', 'history'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 2000,
    highlights: ['Port wine cellars', 'Ribeira', 'Livraria Lello', 'Douro Valley'],
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
    latitude: 41.1579,
    longitude: -8.6291,
  },
  {
    id: 'nice',
    city: 'Nice',
    country: 'France',
    airportCode: 'NCE',
    region: 'europe',
    vibes: ['beach', 'culture', 'luxury', 'food'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 3500,
    highlights: ['Promenade des Anglais', 'Old Town', 'French Riviera', 'Art museums'],
    imageUrl: 'https://images.unsplash.com/photo-1491166617655-0723a0999cfc?w=800',
    latitude: 43.7102,
    longitude: 7.2620,
  },
  {
    id: 'lyon',
    city: 'Lyon',
    country: 'France',
    airportCode: 'LYS',
    region: 'europe',
    vibes: ['food', 'culture', 'history', 'city'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 2500,
    highlights: ['Bouchons', 'Old Lyon', 'Basilica', 'Gastronomy capital'],
    imageUrl: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800',
    latitude: 45.7640,
    longitude: 4.8357,
  },
  {
    id: 'zurich',
    city: 'Zurich',
    country: 'Switzerland',
    airportCode: 'ZRH',
    region: 'europe',
    vibes: ['city', 'culture', 'luxury', 'nature'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 5000,
    highlights: ['Old Town', 'Lake Zurich', 'Art galleries', 'Chocolate shops'],
    imageUrl: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800',
    latitude: 47.3769,
    longitude: 8.5417,
  },
  {
    id: 'geneva',
    city: 'Geneva',
    country: 'Switzerland',
    airportCode: 'GVA',
    region: 'europe',
    vibes: ['city', 'luxury', 'nature', 'culture'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 4800,
    highlights: ['Jet d\'Eau', 'Lake Geneva', 'Old Town', 'CERN'],
    imageUrl: 'https://images.unsplash.com/photo-1573108037329-37aa135a142e?w=800',
    latitude: 46.2044,
    longitude: 6.1432,
  },
  {
    id: 'split',
    city: 'Split',
    country: 'Croatia',
    airportCode: 'SPU',
    region: 'europe',
    vibes: ['beach', 'history', 'culture', 'nightlife'],
    bestMonths: [5, 6, 9],
    averageCost: 2500,
    highlights: ['Diocletian\'s Palace', 'Beaches', 'Island hopping', 'Riva promenade'],
    imageUrl: 'https://images.unsplash.com/photo-1555990538-1e6c2f3d8a2e?w=800',
    latitude: 43.5081,
    longitude: 16.4402,
  },
  {
    id: 'tallinn',
    city: 'Tallinn',
    country: 'Estonia',
    airportCode: 'TLL',
    region: 'europe',
    vibes: ['history', 'culture', 'city', 'nightlife'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 1800,
    highlights: ['Old Town', 'Medieval walls', 'Digital society', 'Craft beer'],
    imageUrl: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800',
    latitude: 59.4370,
    longitude: 24.7536,
  },
  {
    id: 'riga',
    city: 'Riga',
    country: 'Latvia',
    airportCode: 'RIX',
    region: 'europe',
    vibes: ['history', 'culture', 'city', 'nightlife'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 1600,
    highlights: ['Art Nouveau', 'Old Town', 'Central Market', 'Baltic culture'],
    imageUrl: 'https://images.unsplash.com/photo-1539525557625-d7e4e01caba5?w=800',
    latitude: 56.9496,
    longitude: 24.1052,
  },
  {
    id: 'malta',
    city: 'Valletta',
    country: 'Malta',
    airportCode: 'MLA',
    region: 'europe',
    vibes: ['history', 'beach', 'culture', 'city'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 2200,
    highlights: ['Valletta', 'Blue Lagoon', 'Ancient temples', 'Diving'],
    imageUrl: 'https://images.unsplash.com/photo-1514222709107-a180c68d72b4?w=800',
    latitude: 35.8989,
    longitude: 14.5146,
  },
  {
    id: 'corsica',
    city: 'Ajaccio',
    country: 'France',
    airportCode: 'AJA',
    region: 'europe',
    vibes: ['beach', 'nature', 'adventure', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 2800,
    highlights: ['Beaches', 'GR20 trail', 'Napoleon\'s birthplace', 'Scandola Reserve'],
    imageUrl: 'https://images.unsplash.com/photo-1533231144814-a3b32d64b10e?w=800',
    latitude: 41.9192,
    longitude: 8.7386,
  },
  {
    id: 'sardinia',
    city: 'Cagliari',
    country: 'Italy',
    airportCode: 'CAG',
    region: 'europe',
    vibes: ['beach', 'nature', 'food', 'relaxation'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 2800,
    highlights: ['Costa Smeralda', 'Ancient ruins', 'Beaches', 'Sardinian cuisine'],
    imageUrl: 'https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=800',
    latitude: 39.2238,
    longitude: 9.1217,
  },
  {
    id: 'ibiza',
    city: 'Ibiza',
    country: 'Spain',
    airportCode: 'IBZ',
    region: 'europe',
    vibes: ['nightlife', 'beach', 'luxury', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 3500,
    highlights: ['Superclubs', 'Beaches', 'Old Town', 'Sunset bars'],
    imageUrl: 'https://images.unsplash.com/photo-1573126617899-41f1dffb196c?w=800',
    latitude: 38.9067,
    longitude: 1.4206,
  },
  {
    id: 'sicily',
    city: 'Palermo',
    country: 'Italy',
    airportCode: 'PMO',
    region: 'europe',
    vibes: ['history', 'food', 'beach', 'culture'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 2200,
    highlights: ['Mount Etna', 'Greek temples', 'Street food', 'Baroque towns'],
    imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800',
    latitude: 38.1157,
    longitude: 13.3615,
  },
  {
    id: 'canary-islands',
    city: 'Tenerife',
    country: 'Spain',
    airportCode: 'TFS',
    region: 'europe',
    vibes: ['beach', 'nature', 'family', 'adventure'],
    bestMonths: [1, 2, 3, 4, 5, 10, 11, 12],
    averageCost: 2000,
    highlights: ['Mount Teide', 'Beaches', 'Whale watching', 'Year-round sun'],
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    latitude: 28.2916,
    longitude: -16.6291,
  },
  {
    id: 'scottish-highlands',
    city: 'Inverness',
    country: 'United Kingdom',
    airportCode: 'INV',
    region: 'europe',
    vibes: ['nature', 'adventure', 'history', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 2800,
    highlights: ['Loch Ness', 'Castles', 'Whisky distilleries', 'Highlands scenery'],
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    latitude: 57.4778,
    longitude: -4.2247,
  },
  {
    id: 'lapland',
    city: 'Rovaniemi',
    country: 'Finland',
    airportCode: 'RVN',
    region: 'europe',
    vibes: ['nature', 'adventure', 'family'],
    bestMonths: [12, 1, 2, 3, 6, 7],
    averageCost: 4000,
    highlights: ['Northern Lights', 'Santa Claus Village', 'Husky safaris', 'Midnight sun'],
    imageUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    latitude: 66.5039,
    longitude: 25.7294,
  },
  {
    id: 'cinque-terre',
    city: 'La Spezia',
    country: 'Italy',
    airportCode: 'PSA',
    region: 'europe',
    vibes: ['nature', 'romance', 'food', 'beach'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 3000,
    highlights: ['Five villages', 'Hiking trails', 'Seafood', 'Coastal views'],
    imageUrl: 'https://images.unsplash.com/photo-1499678329028-101435549a4e?w=800',
    latitude: 44.1461,
    longitude: 9.6439,
  },

  // ============================================
  // ASIA (~50 destinations)
  // ============================================
  {
    id: 'tokyo',
    city: 'Tokyo',
    country: 'Japan',
    airportCode: 'HND',
    region: 'asia',
    vibes: ['culture', 'city', 'food', 'nightlife'],
    bestMonths: [3, 4, 10, 11],
    averageCost: 4000,
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Sushi Dai', 'Cherry blossoms'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    latitude: 35.6762,
    longitude: 139.6503,
  },
  {
    id: 'bali',
    city: 'Bali',
    country: 'Indonesia',
    airportCode: 'DPS',
    region: 'asia',
    vibes: ['beach', 'relaxation', 'culture', 'nature', 'family'],
    bestMonths: [4, 5, 6, 7, 8, 9],
    averageCost: 2500,
    highlights: ['Ubud rice terraces', 'Uluwatu Temple', 'Beach clubs', 'Yoga retreats'],
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    latitude: -8.4095,
    longitude: 115.1889,
  },
  {
    id: 'bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    airportCode: 'BKK',
    region: 'asia',
    vibes: ['culture', 'food', 'nightlife', 'city'],
    bestMonths: [11, 12, 1, 2],
    averageCost: 2000,
    highlights: ['Grand Palace', 'Street food', 'Floating markets', 'Rooftop bars'],
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    latitude: 13.7563,
    longitude: 100.5018,
  },
  {
    id: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    airportCode: 'SIN',
    region: 'asia',
    vibes: ['city', 'food', 'family', 'luxury'],
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    averageCost: 4000,
    highlights: ['Gardens by the Bay', 'Marina Bay Sands', 'Hawker centers', 'Sentosa'],
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
    latitude: 1.3521,
    longitude: 103.8198,
  },
  {
    id: 'kyoto',
    city: 'Kyoto',
    country: 'Japan',
    airportCode: 'KIX',
    region: 'asia',
    vibes: ['culture', 'history', 'nature', 'relaxation'],
    bestMonths: [3, 4, 10, 11],
    averageCost: 3800,
    highlights: ['Fushimi Inari', 'Geisha district', 'Bamboo grove', 'Tea ceremonies'],
    imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    latitude: 35.0116,
    longitude: 135.7681,
  },
  {
    id: 'vietnam',
    city: 'Ho Chi Minh City',
    country: 'Vietnam',
    airportCode: 'SGN',
    region: 'asia',
    vibes: ['culture', 'food', 'history', 'adventure'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 1800,
    highlights: ['Cu Chi Tunnels', 'Street food tours', 'Mekong Delta', 'War museums'],
    imageUrl: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800',
    latitude: 10.8231,
    longitude: 106.6297,
  },
  {
    id: 'maldives',
    city: 'Maldives',
    country: 'Maldives',
    airportCode: 'MLE',
    region: 'asia',
    vibes: ['beach', 'romance', 'luxury', 'relaxation'],
    bestMonths: [1, 2, 3, 4, 11, 12],
    averageCost: 8000,
    highlights: ['Overwater bungalows', 'Snorkeling', 'Private islands', 'Sunset cruises'],
    imageUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    latitude: 3.2028,
    longitude: 73.2207,
  },
  {
    id: 'hong-kong',
    city: 'Hong Kong',
    country: 'Hong Kong',
    airportCode: 'HKG',
    region: 'asia',
    vibes: ['city', 'food', 'nightlife', 'culture'],
    bestMonths: [10, 11, 12],
    averageCost: 3500,
    highlights: ['Victoria Peak', 'Dim sum', 'Star Ferry', 'Night markets'],
    imageUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800',
    latitude: 22.3193,
    longitude: 114.1694,
  },
  {
    id: 'sri-lanka',
    city: 'Colombo',
    country: 'Sri Lanka',
    airportCode: 'CMB',
    region: 'asia',
    vibes: ['nature', 'culture', 'beach', 'adventure', 'history'],
    bestMonths: [1, 2, 3, 7, 8],
    averageCost: 2000,
    highlights: ['Sigiriya Rock', 'Tea plantations', 'Safari', 'Ancient temples'],
    imageUrl: 'https://images.unsplash.com/photo-1586613836474-85a0a54b66a5?w=800',
    latitude: 6.9271,
    longitude: 79.8612,
  },
  {
    id: 'seoul',
    city: 'Seoul',
    country: 'South Korea',
    airportCode: 'ICN',
    region: 'asia',
    vibes: ['city', 'culture', 'food', 'nightlife'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 3000,
    highlights: ['Gyeongbokgung Palace', 'K-pop culture', 'Korean BBQ', 'Myeongdong'],
    imageUrl: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800',
    latitude: 37.5665,
    longitude: 126.9780,
  },
  {
    id: 'busan',
    city: 'Busan',
    country: 'South Korea',
    airportCode: 'PUS',
    region: 'asia',
    vibes: ['beach', 'city', 'food', 'culture'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 2500,
    highlights: ['Haeundae Beach', 'Jagalchi Market', 'Gamcheon Village', 'Temples'],
    imageUrl: 'https://images.unsplash.com/photo-1578037571214-25e07834a142?w=800',
    latitude: 35.1796,
    longitude: 129.0756,
  },
  {
    id: 'osaka',
    city: 'Osaka',
    country: 'Japan',
    airportCode: 'KIX',
    region: 'asia',
    vibes: ['food', 'city', 'culture', 'nightlife'],
    bestMonths: [3, 4, 10, 11],
    averageCost: 3500,
    highlights: ['Street food', 'Osaka Castle', 'Dotonbori', 'Universal Studios'],
    imageUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800',
    latitude: 34.6937,
    longitude: 135.5023,
  },
  {
    id: 'hanoi',
    city: 'Hanoi',
    country: 'Vietnam',
    airportCode: 'HAN',
    region: 'asia',
    vibes: ['culture', 'food', 'history', 'city'],
    bestMonths: [10, 11, 3, 4],
    averageCost: 1500,
    highlights: ['Old Quarter', 'Pho', 'Halong Bay', 'Temple of Literature'],
    imageUrl: 'https://images.unsplash.com/photo-1509030450996-dd1a26dda07a?w=800',
    latitude: 21.0285,
    longitude: 105.8542,
  },
  {
    id: 'phuket',
    city: 'Phuket',
    country: 'Thailand',
    airportCode: 'HKT',
    region: 'asia',
    vibes: ['beach', 'nightlife', 'family', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 2200,
    highlights: ['Patong Beach', 'Island hopping', 'Thai massages', 'Water sports'],
    imageUrl: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800',
    latitude: 7.8804,
    longitude: 98.3923,
  },
  {
    id: 'chiang-mai',
    city: 'Chiang Mai',
    country: 'Thailand',
    airportCode: 'CNX',
    region: 'asia',
    vibes: ['culture', 'nature', 'food', 'relaxation'],
    bestMonths: [11, 12, 1, 2],
    averageCost: 1500,
    highlights: ['Temples', 'Night markets', 'Elephant sanctuaries', 'Thai cooking'],
    imageUrl: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800',
    latitude: 18.7883,
    longitude: 98.9853,
  },
  {
    id: 'kuala-lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    airportCode: 'KUL',
    region: 'asia',
    vibes: ['city', 'food', 'culture', 'family'],
    bestMonths: [1, 2, 6, 7, 8],
    averageCost: 2000,
    highlights: ['Petronas Towers', 'Batu Caves', 'Street food', 'Shopping'],
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800',
    latitude: 3.1390,
    longitude: 101.6869,
  },
  {
    id: 'langkawi',
    city: 'Langkawi',
    country: 'Malaysia',
    airportCode: 'LGK',
    region: 'asia',
    vibes: ['beach', 'nature', 'relaxation', 'family'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 1800,
    highlights: ['Sky Bridge', 'Island hopping', 'Duty-free shopping', 'Beaches'],
    imageUrl: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800',
    latitude: 6.3500,
    longitude: 99.8000,
  },
  {
    id: 'taipei',
    city: 'Taipei',
    country: 'Taiwan',
    airportCode: 'TPE',
    region: 'asia',
    vibes: ['city', 'food', 'culture', 'nightlife'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2500,
    highlights: ['Taipei 101', 'Night markets', 'Hot springs', 'Jiufen'],
    imageUrl: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?w=800',
    latitude: 25.0330,
    longitude: 121.5654,
  },
  {
    id: 'manila',
    city: 'Manila',
    country: 'Philippines',
    airportCode: 'MNL',
    region: 'asia',
    vibes: ['city', 'culture', 'food', 'nightlife'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 1800,
    highlights: ['Intramuros', 'Malls', 'Filipino cuisine', 'Island gateway'],
    imageUrl: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800',
    latitude: 14.5995,
    longitude: 120.9842,
  },
  {
    id: 'palawan',
    city: 'Puerto Princesa',
    country: 'Philippines',
    airportCode: 'PPS',
    region: 'asia',
    vibes: ['beach', 'nature', 'adventure', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2000,
    highlights: ['El Nido', 'Underground river', 'Island hopping', 'Diving'],
    imageUrl: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800',
    latitude: 9.7392,
    longitude: 118.7353,
  },
  {
    id: 'boracay',
    city: 'Boracay',
    country: 'Philippines',
    airportCode: 'KLO',
    region: 'asia',
    vibes: ['beach', 'nightlife', 'relaxation', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    averageCost: 2200,
    highlights: ['White Beach', 'Water sports', 'Sunsets', 'Beach parties'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    latitude: 11.9674,
    longitude: 121.9248,
  },
  {
    id: 'siem-reap',
    city: 'Siem Reap',
    country: 'Cambodia',
    airportCode: 'REP',
    region: 'asia',
    vibes: ['history', 'culture', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 1500,
    highlights: ['Angkor Wat', 'Temples', 'Night markets', 'Floating villages'],
    imageUrl: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=800',
    latitude: 13.3671,
    longitude: 103.8448,
  },
  {
    id: 'luang-prabang',
    city: 'Luang Prabang',
    country: 'Laos',
    airportCode: 'LPQ',
    region: 'asia',
    vibes: ['culture', 'nature', 'relaxation', 'history'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 1200,
    highlights: ['Monks alms', 'Waterfalls', 'French colonial', 'Mekong cruises'],
    imageUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
    latitude: 19.8840,
    longitude: 102.1347,
  },
  {
    id: 'yangon',
    city: 'Yangon',
    country: 'Myanmar',
    airportCode: 'RGN',
    region: 'asia',
    vibes: ['culture', 'history', 'food'],
    bestMonths: [11, 12, 1, 2],
    averageCost: 1500,
    highlights: ['Shwedagon Pagoda', 'Colonial architecture', 'Street food', 'Markets'],
    imageUrl: 'https://images.unsplash.com/photo-1535139262971-c51845709a48?w=800',
    latitude: 16.8661,
    longitude: 96.1951,
  },
  {
    id: 'kathmandu',
    city: 'Kathmandu',
    country: 'Nepal',
    airportCode: 'KTM',
    region: 'asia',
    vibes: ['culture', 'adventure', 'history', 'nature'],
    bestMonths: [10, 11, 3, 4],
    averageCost: 1500,
    highlights: ['Temples', 'Everest trekking', 'Durbar Square', 'Himalayas'],
    imageUrl: 'https://images.unsplash.com/photo-1558799401-1dcba79834c2?w=800',
    latitude: 27.7172,
    longitude: 85.3240,
  },
  {
    id: 'bhutan',
    city: 'Paro',
    country: 'Bhutan',
    airportCode: 'PBH',
    region: 'asia',
    vibes: ['culture', 'nature', 'adventure', 'relaxation'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    averageCost: 5000,
    highlights: ['Tiger\'s Nest', 'Dzongs', 'Himalayan culture', 'Gross National Happiness'],
    imageUrl: 'https://images.unsplash.com/photo-1553856622-d1b352e24a82?w=800',
    latitude: 27.4287,
    longitude: 89.4164,
  },
  {
    id: 'beijing',
    city: 'Beijing',
    country: 'China',
    airportCode: 'PEK',
    region: 'asia',
    vibes: ['history', 'culture', 'food', 'city'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 2500,
    highlights: ['Great Wall', 'Forbidden City', 'Hutongs', 'Peking duck'],
    imageUrl: 'https://images.unsplash.com/photo-1508804052814-cd3ba865a116?w=800',
    latitude: 39.9042,
    longitude: 116.4074,
  },
  {
    id: 'shanghai',
    city: 'Shanghai',
    country: 'China',
    airportCode: 'PVG',
    region: 'asia',
    vibes: ['city', 'culture', 'food', 'nightlife'],
    bestMonths: [4, 5, 9, 10, 11],
    averageCost: 2800,
    highlights: ['The Bund', 'Yu Garden', 'French Concession', 'Skyscrapers'],
    imageUrl: 'https://images.unsplash.com/photo-1537531383496-f4749b66f58b?w=800',
    latitude: 31.2304,
    longitude: 121.4737,
  },
  {
    id: 'xian',
    city: 'Xi\'an',
    country: 'China',
    airportCode: 'XIY',
    region: 'asia',
    vibes: ['history', 'culture', 'food'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 2000,
    highlights: ['Terracotta Warriors', 'City walls', 'Muslim Quarter', 'Silk Road'],
    imageUrl: 'https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?w=800',
    latitude: 34.3416,
    longitude: 108.9398,
  },
  {
    id: 'guilin',
    city: 'Guilin',
    country: 'China',
    airportCode: 'KWL',
    region: 'asia',
    vibes: ['nature', 'culture', 'relaxation'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 1800,
    highlights: ['Li River', 'Karst mountains', 'Rice terraces', 'Yangshuo'],
    imageUrl: 'https://images.unsplash.com/photo-1537531383496-f4749b66f58b?w=800',
    latitude: 25.2742,
    longitude: 110.2990,
  },
  {
    id: 'hoi-an',
    city: 'Hoi An',
    country: 'Vietnam',
    airportCode: 'DAD',
    region: 'asia',
    vibes: ['culture', 'food', 'beach', 'history'],
    bestMonths: [2, 3, 4],
    averageCost: 1500,
    highlights: ['Ancient town', 'Lanterns', 'Tailors', 'Cooking classes'],
    imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
    latitude: 15.8801,
    longitude: 108.3380,
  },
  {
    id: 'da-nang',
    city: 'Da Nang',
    country: 'Vietnam',
    airportCode: 'DAD',
    region: 'asia',
    vibes: ['beach', 'city', 'food', 'adventure'],
    bestMonths: [2, 3, 4, 5],
    averageCost: 1500,
    highlights: ['Golden Bridge', 'My Khe Beach', 'Marble Mountains', 'Ba Na Hills'],
    imageUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800',
    latitude: 16.0544,
    longitude: 108.2022,
  },
  {
    id: 'kochi',
    city: 'Kochi',
    country: 'India',
    airportCode: 'COK',
    region: 'asia',
    vibes: ['culture', 'food', 'history', 'relaxation'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 1500,
    highlights: ['Chinese fishing nets', 'Backwaters', 'Spice markets', 'Kathakali'],
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800',
    latitude: 9.9312,
    longitude: 76.2673,
  },
  {
    id: 'goa',
    city: 'Goa',
    country: 'India',
    airportCode: 'GOI',
    region: 'asia',
    vibes: ['beach', 'nightlife', 'relaxation', 'culture'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 1200,
    highlights: ['Beaches', 'Portuguese heritage', 'Beach parties', 'Seafood'],
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
    latitude: 15.2993,
    longitude: 74.1240,
  },
  {
    id: 'jaipur',
    city: 'Jaipur',
    country: 'India',
    airportCode: 'JAI',
    region: 'asia',
    vibes: ['history', 'culture', 'city'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 1500,
    highlights: ['Amber Fort', 'Pink City', 'Hawa Mahal', 'Bazaars'],
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800',
    latitude: 26.9124,
    longitude: 75.7873,
  },
  {
    id: 'delhi',
    city: 'New Delhi',
    country: 'India',
    airportCode: 'DEL',
    region: 'asia',
    vibes: ['history', 'culture', 'food', 'city'],
    bestMonths: [10, 11, 12, 2, 3],
    averageCost: 1800,
    highlights: ['Red Fort', 'Qutub Minar', 'Street food', 'Chandni Chowk'],
    imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800',
    latitude: 28.6139,
    longitude: 77.2090,
  },
  {
    id: 'agra',
    city: 'Agra',
    country: 'India',
    airportCode: 'AGR',
    region: 'asia',
    vibes: ['history', 'culture', 'romance'],
    bestMonths: [10, 11, 2, 3],
    averageCost: 1200,
    highlights: ['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri', 'Mughal heritage'],
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800',
    latitude: 27.1767,
    longitude: 78.0081,
  },
  {
    id: 'mumbai',
    city: 'Mumbai',
    country: 'India',
    airportCode: 'BOM',
    region: 'asia',
    vibes: ['city', 'culture', 'food', 'nightlife'],
    bestMonths: [11, 12, 1, 2],
    averageCost: 2000,
    highlights: ['Gateway of India', 'Bollywood', 'Street food', 'Colonial architecture'],
    imageUrl: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=800',
    latitude: 19.0760,
    longitude: 72.8777,
  },
  {
    id: 'lombok',
    city: 'Lombok',
    country: 'Indonesia',
    airportCode: 'LOP',
    region: 'asia',
    vibes: ['beach', 'adventure', 'nature', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 1800,
    highlights: ['Gili Islands', 'Mount Rinjani', 'Surfing', 'Pristine beaches'],
    imageUrl: 'https://images.unsplash.com/photo-1571366343168-631c5bcca7a4?w=800',
    latitude: -8.6500,
    longitude: 116.3249,
  },
  {
    id: 'yogyakarta',
    city: 'Yogyakarta',
    country: 'Indonesia',
    airportCode: 'JOG',
    region: 'asia',
    vibes: ['culture', 'history', 'food'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 1200,
    highlights: ['Borobudur', 'Prambanan', 'Batik', 'Javanese culture'],
    imageUrl: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?w=800',
    latitude: -7.7956,
    longitude: 110.3695,
  },
  {
    id: 'nha-trang',
    city: 'Nha Trang',
    country: 'Vietnam',
    airportCode: 'CXR',
    region: 'asia',
    vibes: ['beach', 'relaxation', 'nightlife', 'adventure'],
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8],
    averageCost: 1300,
    highlights: ['Beaches', 'Diving', 'Mud baths', 'Island hopping'],
    imageUrl: 'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800',
    latitude: 12.2388,
    longitude: 109.1967,
  },

  // ============================================
  // AMERICAS (~50 destinations)
  // ============================================
  {
    id: 'new-york',
    city: 'New York',
    country: 'United States',
    airportCode: 'JFK',
    region: 'americas',
    vibes: ['city', 'culture', 'food', 'nightlife'],
    bestMonths: [4, 5, 9, 10, 12],
    averageCost: 4500,
    highlights: ['Times Square', 'Central Park', 'Broadway', 'Statue of Liberty'],
    imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    latitude: 40.7128,
    longitude: -74.0060,
  },
  {
    id: 'cancun',
    city: 'Cancun',
    country: 'Mexico',
    airportCode: 'CUN',
    region: 'americas',
    vibes: ['beach', 'nightlife', 'family', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2500,
    highlights: ['Beach resorts', 'Chichen Itza', 'Cenotes', 'Underwater museum'],
    imageUrl: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800',
    latitude: 21.1619,
    longitude: -86.8515,
  },
  {
    id: 'costa-rica',
    city: 'San Jose',
    country: 'Costa Rica',
    airportCode: 'SJO',
    region: 'americas',
    vibes: ['adventure', 'nature', 'beach', 'family'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3000,
    highlights: ['Cloud forests', 'Volcano hiking', 'Zip lining', 'Wildlife'],
    imageUrl: 'https://images.unsplash.com/photo-1518259102261-b40117eabbc9?w=800',
    latitude: 9.9281,
    longitude: -84.0907,
  },
  {
    id: 'miami',
    city: 'Miami',
    country: 'United States',
    airportCode: 'MIA',
    region: 'americas',
    vibes: ['beach', 'nightlife', 'city', 'food'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3500,
    highlights: ['South Beach', 'Art Deco district', 'Cuban food', 'Everglades'],
    imageUrl: 'https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?w=800',
    latitude: 25.7617,
    longitude: -80.1918,
  },
  {
    id: 'peru',
    city: 'Cusco',
    country: 'Peru',
    airportCode: 'CUZ',
    region: 'americas',
    vibes: ['adventure', 'history', 'culture', 'nature'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 2800,
    highlights: ['Machu Picchu', 'Sacred Valley', 'Rainbow Mountain', 'Inca Trail'],
    imageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800',
    latitude: -13.5319,
    longitude: -71.9675,
  },
  {
    id: 'rio',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    airportCode: 'GIG',
    region: 'americas',
    vibes: ['beach', 'nightlife', 'culture', 'adventure'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Christ the Redeemer', 'Copacabana', 'Sugarloaf', 'Samba'],
    imageUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
    latitude: -22.9068,
    longitude: -43.1729,
  },
  {
    id: 'buenos-aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    airportCode: 'EZE',
    region: 'americas',
    vibes: ['culture', 'food', 'nightlife', 'city'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2500,
    highlights: ['Tango shows', 'Steak houses', 'La Boca', 'Recoleta Cemetery'],
    imageUrl: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800',
    latitude: -34.6037,
    longitude: -58.3816,
  },
  {
    id: 'hawaii',
    city: 'Honolulu',
    country: 'United States',
    airportCode: 'HNL',
    region: 'americas',
    vibes: ['beach', 'nature', 'relaxation', 'family', 'adventure'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 5000,
    highlights: ['Waikiki Beach', 'Diamond Head', 'Pearl Harbor', 'Luaus'],
    imageUrl: 'https://images.unsplash.com/photo-1507876466758-bc54f384809c?w=800',
    latitude: 21.3069,
    longitude: -157.8583,
  },
  {
    id: 'maui',
    city: 'Maui',
    country: 'United States',
    airportCode: 'OGG',
    region: 'americas',
    vibes: ['beach', 'nature', 'adventure', 'romance', 'relaxation'],
    bestMonths: [4, 5, 9, 10, 11],
    averageCost: 5500,
    highlights: ['Road to Hana', 'Haleakala', 'Whale watching', 'Snorkeling'],
    imageUrl: 'https://images.unsplash.com/photo-1542259009477-d625272157b7?w=800',
    latitude: 20.7984,
    longitude: -156.3319,
  },
  {
    id: 'los-angeles',
    city: 'Los Angeles',
    country: 'United States',
    airportCode: 'LAX',
    region: 'americas',
    vibes: ['city', 'beach', 'culture', 'nightlife'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    averageCost: 4000,
    highlights: ['Hollywood', 'Santa Monica', 'Disneyland', 'Beverly Hills'],
    imageUrl: 'https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=800',
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 'san-francisco',
    city: 'San Francisco',
    country: 'United States',
    airportCode: 'SFO',
    region: 'americas',
    vibes: ['city', 'culture', 'food', 'nature'],
    bestMonths: [9, 10, 11],
    averageCost: 4500,
    highlights: ['Golden Gate Bridge', 'Alcatraz', 'Cable cars', 'Wine country'],
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800',
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 'las-vegas',
    city: 'Las Vegas',
    country: 'United States',
    airportCode: 'LAS',
    region: 'americas',
    vibes: ['nightlife', 'city', 'luxury', 'adventure'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 3000,
    highlights: ['Casinos', 'Shows', 'Grand Canyon', 'Restaurants'],
    imageUrl: 'https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=800',
    latitude: 36.1699,
    longitude: -115.1398,
  },
  {
    id: 'chicago',
    city: 'Chicago',
    country: 'United States',
    airportCode: 'ORD',
    region: 'americas',
    vibes: ['city', 'culture', 'food', 'history'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 3200,
    highlights: ['Architecture', 'Deep dish pizza', 'Art Institute', 'Navy Pier'],
    imageUrl: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=800',
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: 'boston',
    city: 'Boston',
    country: 'United States',
    airportCode: 'BOS',
    region: 'americas',
    vibes: ['history', 'culture', 'city', 'food'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 3500,
    highlights: ['Freedom Trail', 'Harvard', 'Seafood', 'Fall foliage'],
    imageUrl: 'https://images.unsplash.com/photo-1501979376754-00b7747906ef?w=800',
    latitude: 42.3601,
    longitude: -71.0589,
  },
  {
    id: 'washington-dc',
    city: 'Washington D.C.',
    country: 'United States',
    airportCode: 'DCA',
    region: 'americas',
    vibes: ['history', 'culture', 'city'],
    bestMonths: [3, 4, 5, 9, 10],
    averageCost: 3200,
    highlights: ['Smithsonian', 'Monuments', 'Cherry blossoms', 'White House'],
    imageUrl: 'https://images.unsplash.com/photo-1501466044931-62695aada8e9?w=800',
    latitude: 38.9072,
    longitude: -77.0369,
  },
  {
    id: 'seattle',
    city: 'Seattle',
    country: 'United States',
    airportCode: 'SEA',
    region: 'americas',
    vibes: ['city', 'nature', 'food', 'culture'],
    bestMonths: [6, 7, 8, 9],
    averageCost: 3500,
    highlights: ['Space Needle', 'Pike Place', 'Coffee culture', 'Mount Rainier'],
    imageUrl: 'https://images.unsplash.com/photo-1502175353174-a7a70e73b362?w=800',
    latitude: 47.6062,
    longitude: -122.3321,
  },
  {
    id: 'new-orleans',
    city: 'New Orleans',
    country: 'United States',
    airportCode: 'MSY',
    region: 'americas',
    vibes: ['nightlife', 'food', 'culture', 'history'],
    bestMonths: [2, 3, 10, 11, 12],
    averageCost: 2800,
    highlights: ['French Quarter', 'Jazz', 'Cajun food', 'Mardi Gras'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 29.9511,
    longitude: -90.0715,
  },
  {
    id: 'austin',
    city: 'Austin',
    country: 'United States',
    airportCode: 'AUS',
    region: 'americas',
    vibes: ['nightlife', 'food', 'culture', 'city'],
    bestMonths: [3, 4, 10, 11],
    averageCost: 2800,
    highlights: ['Live music', 'BBQ', 'Food trucks', 'SXSW'],
    imageUrl: 'https://images.unsplash.com/photo-1531218150217-54595bc2b934?w=800',
    latitude: 30.2672,
    longitude: -97.7431,
  },
  {
    id: 'nashville',
    city: 'Nashville',
    country: 'United States',
    airportCode: 'BNA',
    region: 'americas',
    vibes: ['nightlife', 'culture', 'food', 'city'],
    bestMonths: [4, 5, 9, 10],
    averageCost: 2500,
    highlights: ['Country music', 'Honky-tonks', 'Hot chicken', 'Grand Ole Opry'],
    imageUrl: 'https://images.unsplash.com/photo-1496568816309-51d7c20e3b21?w=800',
    latitude: 36.1627,
    longitude: -86.7816,
  },
  {
    id: 'san-diego',
    city: 'San Diego',
    country: 'United States',
    airportCode: 'SAN',
    region: 'americas',
    vibes: ['beach', 'city', 'family', 'food'],
    bestMonths: [5, 6, 9, 10],
    averageCost: 3200,
    highlights: ['Beaches', 'Zoo', 'Gaslamp Quarter', 'Mexican food'],
    imageUrl: 'https://images.unsplash.com/photo-1538970272646-f61fabb3a8a2?w=800',
    latitude: 32.7157,
    longitude: -117.1611,
  },
  {
    id: 'toronto',
    city: 'Toronto',
    country: 'Canada',
    airportCode: 'YYZ',
    region: 'americas',
    vibes: ['city', 'culture', 'food', 'family'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 3000,
    highlights: ['CN Tower', 'Multicultural food', 'Niagara Falls', 'Islands'],
    imageUrl: 'https://images.unsplash.com/photo-1517090504586-fde19ea6066f?w=800',
    latitude: 43.6532,
    longitude: -79.3832,
  },
  {
    id: 'vancouver',
    city: 'Vancouver',
    country: 'Canada',
    airportCode: 'YVR',
    region: 'americas',
    vibes: ['city', 'nature', 'food', 'adventure'],
    bestMonths: [6, 7, 8, 9],
    averageCost: 3500,
    highlights: ['Stanley Park', 'Mountains', 'Sushi', 'Whistler'],
    imageUrl: 'https://images.unsplash.com/photo-1559511260-66a68e7a8c5d?w=800',
    latitude: 49.2827,
    longitude: -123.1207,
  },
  {
    id: 'montreal',
    city: 'Montreal',
    country: 'Canada',
    airportCode: 'YUL',
    region: 'americas',
    vibes: ['culture', 'food', 'nightlife', 'city'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 2500,
    highlights: ['Old Montreal', 'Bagels', 'Festivals', 'French culture'],
    imageUrl: 'https://images.unsplash.com/photo-1519178614-68673b201f36?w=800',
    latitude: 45.5017,
    longitude: -73.5673,
  },
  {
    id: 'banff',
    city: 'Banff',
    country: 'Canada',
    airportCode: 'YYC',
    region: 'americas',
    vibes: ['nature', 'adventure', 'relaxation'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    averageCost: 4000,
    highlights: ['Lake Louise', 'Rocky Mountains', 'Skiing', 'Hot springs'],
    imageUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800',
    latitude: 51.1784,
    longitude: -115.5708,
  },
  {
    id: 'mexico-city',
    city: 'Mexico City',
    country: 'Mexico',
    airportCode: 'MEX',
    region: 'americas',
    vibes: ['culture', 'food', 'history', 'city'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 1800,
    highlights: ['Frida Kahlo', 'Tacos', 'Teotihuacan', 'Zocalo'],
    imageUrl: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800',
    latitude: 19.4326,
    longitude: -99.1332,
  },
  {
    id: 'oaxaca',
    city: 'Oaxaca',
    country: 'Mexico',
    airportCode: 'OAX',
    region: 'americas',
    vibes: ['culture', 'food', 'history'],
    bestMonths: [10, 11, 3, 4],
    averageCost: 1500,
    highlights: ['Mezcal', 'Monte Alban', 'Day of the Dead', 'Mole'],
    imageUrl: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800',
    latitude: 17.0732,
    longitude: -96.7266,
  },
  {
    id: 'tulum',
    city: 'Tulum',
    country: 'Mexico',
    airportCode: 'CUN',
    region: 'americas',
    vibes: ['beach', 'relaxation', 'culture', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    averageCost: 2800,
    highlights: ['Ruins', 'Cenotes', 'Beach clubs', 'Eco-resorts'],
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=800',
    latitude: 20.2114,
    longitude: -87.4654,
  },
  {
    id: 'playa-del-carmen',
    city: 'Playa del Carmen',
    country: 'Mexico',
    airportCode: 'CUN',
    region: 'americas',
    vibes: ['beach', 'nightlife', 'relaxation', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    averageCost: 2500,
    highlights: ['5th Avenue', 'Beach clubs', 'Cozumel', 'Cenotes'],
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800',
    latitude: 20.6296,
    longitude: -87.0739,
  },
  {
    id: 'puerto-vallarta',
    city: 'Puerto Vallarta',
    country: 'Mexico',
    airportCode: 'PVR',
    region: 'americas',
    vibes: ['beach', 'romance', 'food', 'nightlife'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    averageCost: 2200,
    highlights: ['Malecon', 'Old Town', 'Whale watching', 'Beach resorts'],
    imageUrl: 'https://images.unsplash.com/photo-1512813195386-6cf811ad3542?w=800',
    latitude: 20.6534,
    longitude: -105.2253,
  },
  {
    id: 'cartagena',
    city: 'Cartagena',
    country: 'Colombia',
    airportCode: 'CTG',
    region: 'americas',
    vibes: ['history', 'beach', 'culture', 'romance'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 2000,
    highlights: ['Walled city', 'Rosario Islands', 'Colonial architecture', 'Nightlife'],
    imageUrl: 'https://images.unsplash.com/photo-1583531172005-2e2e2e2e2e2e?w=800',
    latitude: 10.3910,
    longitude: -75.4794,
  },
  {
    id: 'medellin',
    city: 'Medellin',
    country: 'Colombia',
    airportCode: 'MDE',
    region: 'americas',
    vibes: ['city', 'culture', 'nightlife', 'nature'],
    bestMonths: [12, 1, 2, 3, 6, 7, 8],
    averageCost: 1800,
    highlights: ['Eternal spring', 'Communa 13', 'Coffee farms', 'Nightlife'],
    imageUrl: 'https://images.unsplash.com/photo-1583531172005-2e2e2e2e2e2e?w=800',
    latitude: 6.2476,
    longitude: -75.5658,
  },
  {
    id: 'bogota',
    city: 'Bogota',
    country: 'Colombia',
    airportCode: 'BOG',
    region: 'americas',
    vibes: ['city', 'culture', 'food', 'history'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 1800,
    highlights: ['La Candelaria', 'Gold Museum', 'Street art', 'Food tours'],
    imageUrl: 'https://images.unsplash.com/photo-1583531172005-2e2e2e2e2e2e?w=800',
    latitude: 4.7110,
    longitude: -74.0721,
  },
  {
    id: 'quito',
    city: 'Quito',
    country: 'Ecuador',
    airportCode: 'UIO',
    region: 'americas',
    vibes: ['history', 'culture', 'nature', 'adventure'],
    bestMonths: [6, 7, 8, 9],
    averageCost: 1800,
    highlights: ['Colonial center', 'Middle of the World', 'Cloud forests', 'Galapagos gateway'],
    imageUrl: 'https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=800',
    latitude: -0.1807,
    longitude: -78.4678,
  },
  {
    id: 'galapagos',
    city: 'Galapagos Islands',
    country: 'Ecuador',
    airportCode: 'GPS',
    region: 'americas',
    vibes: ['nature', 'adventure', 'relaxation'],
    bestMonths: [6, 7, 8, 9, 12, 1],
    averageCost: 6000,
    highlights: ['Wildlife', 'Diving', 'Unique species', 'Volcanic landscapes'],
    imageUrl: 'https://images.unsplash.com/photo-1544979590-37e9b47eb705?w=800',
    latitude: -0.7432,
    longitude: -90.3037,
  },
  {
    id: 'lima',
    city: 'Lima',
    country: 'Peru',
    airportCode: 'LIM',
    region: 'americas',
    vibes: ['food', 'culture', 'history', 'city'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 2200,
    highlights: ['Ceviche', 'Miraflores', 'Historic center', 'World\'s best restaurants'],
    imageUrl: 'https://images.unsplash.com/photo-1531968455001-5c5272a41129?w=800',
    latitude: -12.0464,
    longitude: -77.0428,
  },
  {
    id: 'santiago',
    city: 'Santiago',
    country: 'Chile',
    airportCode: 'SCL',
    region: 'americas',
    vibes: ['city', 'food', 'culture', 'nature'],
    bestMonths: [10, 11, 12, 3, 4],
    averageCost: 2500,
    highlights: ['Wine valleys', 'Andes views', 'Bellavista', 'Museums'],
    imageUrl: 'https://images.unsplash.com/photo-1569701813229-33284b643e3c?w=800',
    latitude: -33.4489,
    longitude: -70.6693,
  },
  {
    id: 'patagonia',
    city: 'Punta Arenas',
    country: 'Chile',
    airportCode: 'PUQ',
    region: 'americas',
    vibes: ['nature', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 4500,
    highlights: ['Torres del Paine', 'Glaciers', 'Hiking', 'Wildlife'],
    imageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800',
    latitude: -53.1638,
    longitude: -70.9171,
  },
  {
    id: 'montevideo',
    city: 'Montevideo',
    country: 'Uruguay',
    airportCode: 'MVD',
    region: 'americas',
    vibes: ['city', 'beach', 'culture', 'food'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 2200,
    highlights: ['Old Town', 'Beaches', 'Mercado del Puerto', 'Wine'],
    imageUrl: 'https://images.unsplash.com/photo-1569701813229-33284b643e3c?w=800',
    latitude: -34.9011,
    longitude: -56.1645,
  },
  {
    id: 'punta-del-este',
    city: 'Punta del Este',
    country: 'Uruguay',
    airportCode: 'PDP',
    region: 'americas',
    vibes: ['beach', 'luxury', 'nightlife'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 3500,
    highlights: ['Beaches', 'La Mano sculpture', 'Nightlife', 'Casinos'],
    imageUrl: 'https://images.unsplash.com/photo-1569701813229-33284b643e3c?w=800',
    latitude: -34.9667,
    longitude: -54.9500,
  },
  {
    id: 'la-paz',
    city: 'La Paz',
    country: 'Bolivia',
    airportCode: 'LPB',
    region: 'americas',
    vibes: ['culture', 'adventure', 'history'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 1500,
    highlights: ['Highest capital', 'Witches Market', 'Moon Valley', 'Cable cars'],
    imageUrl: 'https://images.unsplash.com/photo-1591024190tried-51a4e8b8e8d9?w=800',
    latitude: -16.4897,
    longitude: -68.1193,
  },
  {
    id: 'salar-de-uyuni',
    city: 'Uyuni',
    country: 'Bolivia',
    airportCode: 'UYU',
    region: 'americas',
    vibes: ['nature', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2000,
    highlights: ['Salt flats', 'Mirror effect', 'Desert landscapes', 'Flamingos'],
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    latitude: -20.4606,
    longitude: -66.8262,
  },
  {
    id: 'belize',
    city: 'Belize City',
    country: 'Belize',
    airportCode: 'BZE',
    region: 'americas',
    vibes: ['beach', 'adventure', 'nature', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2500,
    highlights: ['Great Blue Hole', 'Barrier reef', 'Mayan ruins', 'Jungle'],
    imageUrl: 'https://images.unsplash.com/photo-1548402096-8fb11a5f6b4c?w=800',
    latitude: 17.4985,
    longitude: -88.1866,
  },
  {
    id: 'panama',
    city: 'Panama City',
    country: 'Panama',
    airportCode: 'PTY',
    region: 'americas',
    vibes: ['city', 'beach', 'history', 'nature'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2500,
    highlights: ['Panama Canal', 'Casco Viejo', 'San Blas Islands', 'Skyline'],
    imageUrl: 'https://images.unsplash.com/photo-1555990538-1e6c2f3d8a2e?w=800',
    latitude: 8.9824,
    longitude: -79.5199,
  },

  // ============================================
  // CARIBBEAN (~20 destinations)
  // ============================================
  {
    id: 'jamaica',
    city: 'Montego Bay',
    country: 'Jamaica',
    airportCode: 'MBJ',
    region: 'caribbean',
    vibes: ['beach', 'relaxation', 'nightlife', 'culture'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3000,
    highlights: ['All-inclusive resorts', 'Dunn\'s River Falls', 'Reggae', 'Jerk cuisine'],
    imageUrl: 'https://images.unsplash.com/photo-1580237541049-2d715a09486e?w=800',
    latitude: 18.4762,
    longitude: -77.8939,
  },
  {
    id: 'bahamas',
    city: 'Nassau',
    country: 'Bahamas',
    airportCode: 'NAS',
    region: 'caribbean',
    vibes: ['beach', 'luxury', 'family', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 4500,
    highlights: ['Atlantis Resort', 'Swimming pigs', 'Clear waters', 'Island hopping'],
    imageUrl: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800',
    latitude: 25.0343,
    longitude: -77.3963,
  },
  {
    id: 'aruba',
    city: 'Oranjestad',
    country: 'Aruba',
    airportCode: 'AUA',
    region: 'caribbean',
    vibes: ['beach', 'relaxation', 'romance', 'adventure'],
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    averageCost: 3500,
    highlights: ['Eagle Beach', 'Natural bridges', 'Flamingos', 'Water sports'],
    imageUrl: 'https://images.unsplash.com/photo-1548963670-aaaa8f73a5e3?w=800',
    latitude: 12.5211,
    longitude: -69.9683,
  },
  {
    id: 'st-lucia',
    city: 'Castries',
    country: 'Saint Lucia',
    airportCode: 'UVF',
    region: 'caribbean',
    vibes: ['romance', 'beach', 'nature', 'luxury', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4, 5],
    averageCost: 4500,
    highlights: ['Pitons', 'Rainforest', 'Volcanic beaches', 'Luxury resorts'],
    imageUrl: 'https://images.unsplash.com/photo-1499002238440-d264f5e7e7fe?w=800',
    latitude: 14.0101,
    longitude: -60.9870,
  },
  {
    id: 'barbados',
    city: 'Bridgetown',
    country: 'Barbados',
    airportCode: 'BGI',
    region: 'caribbean',
    vibes: ['beach', 'culture', 'food', 'nightlife'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3500,
    highlights: ['Rum distilleries', 'Beaches', 'Flying fish', 'Crop Over festival'],
    imageUrl: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=800',
    latitude: 13.1939,
    longitude: -59.5432,
  },
  {
    id: 'turks-caicos',
    city: 'Providenciales',
    country: 'Turks and Caicos',
    airportCode: 'PLS',
    region: 'caribbean',
    vibes: ['beach', 'luxury', 'relaxation', 'romance'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 5000,
    highlights: ['Grace Bay Beach', 'Diving', 'Luxury resorts', 'Clear waters'],
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    latitude: 21.7737,
    longitude: -72.2081,
  },
  {
    id: 'curacao',
    city: 'Willemstad',
    country: 'Curacao',
    airportCode: 'CUR',
    region: 'caribbean',
    vibes: ['culture', 'beach', 'history', 'adventure'],
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    averageCost: 2800,
    highlights: ['Colorful buildings', 'Beaches', 'Diving', 'Dutch heritage'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 12.1696,
    longitude: -68.9900,
  },
  {
    id: 'dominican-republic',
    city: 'Punta Cana',
    country: 'Dominican Republic',
    airportCode: 'PUJ',
    region: 'caribbean',
    vibes: ['beach', 'family', 'relaxation', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2500,
    highlights: ['All-inclusive resorts', 'Beaches', 'Golf', 'Water sports'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 18.5601,
    longitude: -68.3725,
  },
  {
    id: 'puerto-rico',
    city: 'San Juan',
    country: 'Puerto Rico',
    airportCode: 'SJU',
    region: 'caribbean',
    vibes: ['culture', 'beach', 'history', 'nightlife'],
    bestMonths: [12, 1, 2, 3, 4, 5],
    averageCost: 2800,
    highlights: ['Old San Juan', 'Bioluminescent bays', 'El Yunque', 'Mofongo'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 18.4655,
    longitude: -66.1057,
  },
  {
    id: 'virgin-islands',
    city: 'St. Thomas',
    country: 'US Virgin Islands',
    airportCode: 'STT',
    region: 'caribbean',
    vibes: ['beach', 'relaxation', 'adventure', 'family'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3500,
    highlights: ['Magens Bay', 'Duty-free shopping', 'Sailing', 'Snorkeling'],
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    latitude: 18.3358,
    longitude: -64.8963,
  },
  {
    id: 'cayman-islands',
    city: 'George Town',
    country: 'Cayman Islands',
    airportCode: 'GCM',
    region: 'caribbean',
    vibes: ['beach', 'adventure', 'luxury', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 4500,
    highlights: ['Seven Mile Beach', 'Stingray City', 'Diving', 'Luxury resorts'],
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    latitude: 19.2869,
    longitude: -81.3674,
  },
  {
    id: 'antigua',
    city: 'St. John\'s',
    country: 'Antigua and Barbuda',
    airportCode: 'ANU',
    region: 'caribbean',
    vibes: ['beach', 'relaxation', 'relaxation', 'romance'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3800,
    highlights: ['365 beaches', 'Nelson\'s Dockyard', 'Sailing week', 'Resorts'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 17.1274,
    longitude: -61.8468,
  },
  {
    id: 'grenada',
    city: 'St. George\'s',
    country: 'Grenada',
    airportCode: 'GND',
    region: 'caribbean',
    vibes: ['beach', 'nature', 'adventure', 'culture'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3000,
    highlights: ['Spice island', 'Grand Anse Beach', 'Waterfalls', 'Diving'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 12.0561,
    longitude: -61.7488,
  },
  {
    id: 'st-barts',
    city: 'Gustavia',
    country: 'Saint Barthelemy',
    airportCode: 'SBH',
    region: 'caribbean',
    vibes: ['luxury', 'beach', 'romance', 'food'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 8000,
    highlights: ['French cuisine', 'Designer shopping', 'Beaches', 'Yachts'],
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    latitude: 17.8961,
    longitude: -62.8498,
  },
  {
    id: 'st-kitts',
    city: 'Basseterre',
    country: 'Saint Kitts and Nevis',
    airportCode: 'SKB',
    region: 'caribbean',
    vibes: ['beach', 'history', 'nature', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3200,
    highlights: ['Brimstone Hill', 'Railway', 'Beaches', 'Rainforest'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 17.3026,
    longitude: -62.7177,
  },
  {
    id: 'bonaire',
    city: 'Kralendijk',
    country: 'Bonaire',
    airportCode: 'BON',
    region: 'caribbean',
    vibes: ['adventure', 'beach', 'nature', 'relaxation'],
    bestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    averageCost: 2800,
    highlights: ['Shore diving', 'Flamingos', 'Marine park', 'Windsurfing'],
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
    latitude: 12.2019,
    longitude: -68.2624,
  },
  {
    id: 'martinique',
    city: 'Fort-de-France',
    country: 'Martinique',
    airportCode: 'FDF',
    region: 'caribbean',
    vibes: ['culture', 'beach', 'food', 'nature'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3000,
    highlights: ['French culture', 'Mount Pelee', 'Rum', 'Beaches'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 14.6415,
    longitude: -61.0242,
  },
  {
    id: 'guadeloupe',
    city: 'Pointe-a-Pitre',
    country: 'Guadeloupe',
    airportCode: 'PTP',
    region: 'caribbean',
    vibes: ['beach', 'nature', 'culture', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 2800,
    highlights: ['Butterfly-shaped island', 'Waterfalls', 'Creole culture', 'Diving'],
    imageUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=800',
    latitude: 16.2650,
    longitude: -61.5510,
  },

  // ============================================
  // MIDDLE EAST (~15 destinations)
  // ============================================
  {
    id: 'dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    airportCode: 'DXB',
    region: 'middle_east',
    vibes: ['luxury', 'city', 'beach', 'family'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 5000,
    highlights: ['Burj Khalifa', 'Desert safari', 'Dubai Mall', 'Palm Jumeirah'],
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
    latitude: 25.2048,
    longitude: 55.2708,
  },
  {
    id: 'jordan',
    city: 'Amman',
    country: 'Jordan',
    airportCode: 'AMM',
    region: 'middle_east',
    vibes: ['history', 'adventure', 'culture'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2500,
    highlights: ['Petra', 'Dead Sea', 'Wadi Rum', 'Roman ruins'],
    imageUrl: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=800',
    latitude: 31.9454,
    longitude: 35.9284,
  },
  {
    id: 'israel',
    city: 'Tel Aviv',
    country: 'Israel',
    airportCode: 'TLV',
    region: 'middle_east',
    vibes: ['beach', 'culture', 'food', 'nightlife', 'history'],
    bestMonths: [4, 5, 10, 11],
    averageCost: 3500,
    highlights: ['Old Jaffa', 'Beaches', 'Bauhaus architecture', 'Jerusalem day trips'],
    imageUrl: 'https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=800',
    latitude: 32.0853,
    longitude: 34.7818,
  },
  {
    id: 'oman',
    city: 'Muscat',
    country: 'Oman',
    airportCode: 'MCT',
    region: 'middle_east',
    vibes: ['culture', 'adventure', 'beach', 'history'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Grand Mosque', 'Wadis', 'Desert camping', 'Coastal fjords'],
    imageUrl: 'https://images.unsplash.com/photo-1597466599360-3b9775841aec?w=800',
    latitude: 23.5880,
    longitude: 58.3829,
  },
  {
    id: 'abu-dhabi',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    airportCode: 'AUH',
    region: 'middle_east',
    vibes: ['luxury', 'culture', 'city', 'family'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 4500,
    highlights: ['Sheikh Zayed Mosque', 'Louvre Abu Dhabi', 'Yas Island', 'Desert'],
    imageUrl: 'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=800',
    latitude: 24.4539,
    longitude: 54.3773,
  },
  {
    id: 'doha',
    city: 'Doha',
    country: 'Qatar',
    airportCode: 'DOH',
    region: 'middle_east',
    vibes: ['luxury', 'culture', 'city'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 4000,
    highlights: ['Museum of Islamic Art', 'Souq Waqif', 'Pearl-Qatar', 'Desert'],
    imageUrl: 'https://images.unsplash.com/photo-1559881103-f5f50fa8cfe7?w=800',
    latitude: 25.2867,
    longitude: 51.5333,
  },
  {
    id: 'bahrain',
    city: 'Manama',
    country: 'Bahrain',
    airportCode: 'BAH',
    region: 'middle_east',
    vibes: ['culture', 'city', 'history'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 2800,
    highlights: ['Bahrain Fort', 'Souks', 'F1 Grand Prix', 'Pearl diving heritage'],
    imageUrl: 'https://images.unsplash.com/photo-1559881103-f5f50fa8cfe7?w=800',
    latitude: 26.2285,
    longitude: 50.5860,
  },
  {
    id: 'kuwait',
    city: 'Kuwait City',
    country: 'Kuwait',
    airportCode: 'KWI',
    region: 'middle_east',
    vibes: ['culture', 'city', 'history'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Kuwait Towers', 'Grand Mosque', 'Souks', 'Modern architecture'],
    imageUrl: 'https://images.unsplash.com/photo-1559881103-f5f50fa8cfe7?w=800',
    latitude: 29.3759,
    longitude: 47.9774,
  },
  {
    id: 'jerusalem',
    city: 'Jerusalem',
    country: 'Israel',
    airportCode: 'TLV',
    region: 'middle_east',
    vibes: ['history', 'culture', 'city'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 3500,
    highlights: ['Old City', 'Western Wall', 'Church of Holy Sepulchre', 'Dome of the Rock'],
    imageUrl: 'https://images.unsplash.com/photo-1552423310-ba74b8de4c53?w=800',
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    id: 'dead-sea',
    city: 'Dead Sea',
    country: 'Jordan',
    airportCode: 'AMM',
    region: 'middle_east',
    vibes: ['relaxation', 'nature', 'adventure'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2800,
    highlights: ['Floating', 'Mud baths', 'Resorts', 'Lowest point on Earth'],
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
    latitude: 31.5000,
    longitude: 35.5000,
  },
  {
    id: 'beirut',
    city: 'Beirut',
    country: 'Lebanon',
    airportCode: 'BEY',
    region: 'middle_east',
    vibes: ['culture', 'food', 'nightlife', 'history'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 2500,
    highlights: ['Nightlife', 'Food scene', 'Roman ruins', 'Mediterranean coast'],
    imageUrl: 'https://images.unsplash.com/photo-1549918864-48ac978761a4?w=800',
    latitude: 33.8938,
    longitude: 35.5018,
  },
  {
    id: 'riyadh',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    airportCode: 'RUH',
    region: 'middle_east',
    vibes: ['culture', 'city', 'history'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 3500,
    highlights: ['Edge of the World', 'Diriyah', 'Kingdom Centre', 'Entertainment'],
    imageUrl: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800',
    latitude: 24.7136,
    longitude: 46.6753,
  },
  {
    id: 'jeddah',
    city: 'Jeddah',
    country: 'Saudi Arabia',
    airportCode: 'JED',
    region: 'middle_east',
    vibes: ['culture', 'history', 'beach'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Al-Balad', 'Corniche', 'Red Sea diving', 'Gateway to Mecca'],
    imageUrl: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800',
    latitude: 21.5433,
    longitude: 39.1728,
  },
  {
    id: 'alula',
    city: 'AlUla',
    country: 'Saudi Arabia',
    airportCode: 'ULH',
    region: 'middle_east',
    vibes: ['history', 'adventure', 'nature', 'culture'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 4500,
    highlights: ['Hegra', 'Rock formations', 'Desert luxury', 'Ancient Nabataean'],
    imageUrl: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?w=800',
    latitude: 26.6174,
    longitude: 37.9163,
  },

  // ============================================
  // AFRICA (~25 destinations)
  // ============================================
  {
    id: 'cape-town',
    city: 'Cape Town',
    country: 'South Africa',
    airportCode: 'CPT',
    region: 'africa',
    vibes: ['adventure', 'nature', 'food', 'beach', 'culture'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 3000,
    highlights: ['Table Mountain', 'Wine country', 'Cape of Good Hope', 'Penguins'],
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800',
    latitude: -33.9249,
    longitude: 18.4241,
  },
  {
    id: 'morocco',
    city: 'Marrakech',
    country: 'Morocco',
    airportCode: 'RAK',
    region: 'africa',
    vibes: ['culture', 'food', 'adventure', 'history'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 2000,
    highlights: ['Medina', 'Souks', 'Riads', 'Sahara excursions'],
    imageUrl: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800',
    latitude: 31.6295,
    longitude: -7.9811,
  },
  {
    id: 'tanzania',
    city: 'Arusha',
    country: 'Tanzania',
    airportCode: 'JRO',
    region: 'africa',
    vibes: ['adventure', 'nature', 'family'],
    bestMonths: [6, 7, 8, 9, 1, 2],
    averageCost: 6000,
    highlights: ['Serengeti safari', 'Ngorongoro Crater', 'Zanzibar', 'Kilimanjaro'],
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    latitude: -3.3869,
    longitude: 36.6830,
  },
  {
    id: 'egypt',
    city: 'Cairo',
    country: 'Egypt',
    airportCode: 'CAI',
    region: 'africa',
    vibes: ['history', 'culture', 'adventure'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 2500,
    highlights: ['Pyramids of Giza', 'Nile cruise', 'Luxor temples', 'Abu Simbel'],
    imageUrl: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800',
    latitude: 30.0444,
    longitude: 31.2357,
  },
  {
    id: 'mauritius',
    city: 'Port Louis',
    country: 'Mauritius',
    airportCode: 'MRU',
    region: 'africa',
    vibes: ['beach', 'romance', 'luxury', 'relaxation', 'nature'],
    bestMonths: [5, 6, 7, 8, 9, 10, 11],
    averageCost: 4500,
    highlights: ['Underwater waterfall', 'Beaches', 'Resorts', 'Seven Colored Earths'],
    imageUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800',
    latitude: -20.1609,
    longitude: 57.5012,
  },
  {
    id: 'zanzibar',
    city: 'Stone Town',
    country: 'Tanzania',
    airportCode: 'ZNZ',
    region: 'africa',
    vibes: ['beach', 'culture', 'history', 'relaxation'],
    bestMonths: [6, 7, 8, 9, 1, 2],
    averageCost: 2500,
    highlights: ['Spice tours', 'Stone Town', 'Beaches', 'Dhow sailing'],
    imageUrl: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=800',
    latitude: -6.1622,
    longitude: 39.1921,
  },
  {
    id: 'kenya',
    city: 'Nairobi',
    country: 'Kenya',
    airportCode: 'NBO',
    region: 'africa',
    vibes: ['adventure', 'nature', 'culture'],
    bestMonths: [6, 7, 8, 9, 10, 1, 2],
    averageCost: 5000,
    highlights: ['Masai Mara', 'Big Five', 'Great Migration', 'Giraffe Centre'],
    imageUrl: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6?w=800',
    latitude: -1.2921,
    longitude: 36.8219,
  },
  {
    id: 'seychelles',
    city: 'Mahe',
    country: 'Seychelles',
    airportCode: 'SEZ',
    region: 'africa',
    vibes: ['beach', 'romance', 'luxury', 'nature'],
    bestMonths: [4, 5, 10, 11],
    averageCost: 6000,
    highlights: ['Granite beaches', 'Giant tortoises', 'Diving', 'Luxury resorts'],
    imageUrl: 'https://images.unsplash.com/photo-1589979481223-deb893043163?w=800',
    latitude: -4.6796,
    longitude: 55.4920,
  },
  {
    id: 'victoria-falls',
    city: 'Victoria Falls',
    country: 'Zimbabwe',
    airportCode: 'VFA',
    region: 'africa',
    vibes: ['adventure', 'nature'],
    bestMonths: [6, 7, 8, 9],
    averageCost: 3500,
    highlights: ['Waterfall', 'Bungee jumping', 'Safari', 'Devil\'s Pool'],
    imageUrl: 'https://images.unsplash.com/photo-1568636915207-7acd0a7f8cc5?w=800',
    latitude: -17.9243,
    longitude: 25.8572,
  },
  {
    id: 'johannesburg',
    city: 'Johannesburg',
    country: 'South Africa',
    airportCode: 'JNB',
    region: 'africa',
    vibes: ['city', 'culture', 'history'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    averageCost: 2500,
    highlights: ['Apartheid Museum', 'Soweto', 'Maboneng', 'Safari gateway'],
    imageUrl: 'https://images.unsplash.com/photo-1577948000111-9c970dfe3743?w=800',
    latitude: -26.2041,
    longitude: 28.0473,
  },
  {
    id: 'kruger',
    city: 'Kruger Park',
    country: 'South Africa',
    airportCode: 'MQP',
    region: 'africa',
    vibes: ['adventure', 'nature'],
    bestMonths: [5, 6, 7, 8, 9],
    averageCost: 4000,
    highlights: ['Big Five', 'Safari lodges', 'Bush walks', 'Wildlife'],
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    latitude: -23.9884,
    longitude: 31.5547,
  },
  {
    id: 'fes',
    city: 'Fes',
    country: 'Morocco',
    airportCode: 'FEZ',
    region: 'africa',
    vibes: ['culture', 'history', 'food'],
    bestMonths: [3, 4, 5, 10, 11],
    averageCost: 1800,
    highlights: ['Medina', 'Tanneries', 'Madrasas', 'Artisan crafts'],
    imageUrl: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800',
    latitude: 34.0181,
    longitude: -5.0078,
  },
  {
    id: 'chefchaouen',
    city: 'Chefchaouen',
    country: 'Morocco',
    airportCode: 'TNG',
    region: 'africa',
    vibes: ['culture', 'relaxation', 'nature'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    averageCost: 1500,
    highlights: ['Blue city', 'Medina', 'Rif Mountains', 'Artisan crafts'],
    imageUrl: 'https://images.unsplash.com/photo-1553501747-3b55996a78f2?w=800',
    latitude: 35.1688,
    longitude: -5.2636,
  },
  {
    id: 'essaouira',
    city: 'Essaouira',
    country: 'Morocco',
    airportCode: 'RAK',
    region: 'africa',
    vibes: ['beach', 'culture', 'relaxation'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 1500,
    highlights: ['Medina', 'Windsurfing', 'Fresh seafood', 'Game of Thrones'],
    imageUrl: 'https://images.unsplash.com/photo-1548019979-0e1a96d08c23?w=800',
    latitude: 31.5085,
    longitude: -9.7595,
  },
  {
    id: 'luxor',
    city: 'Luxor',
    country: 'Egypt',
    airportCode: 'LXR',
    region: 'africa',
    vibes: ['history', 'culture', 'adventure'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 2000,
    highlights: ['Valley of Kings', 'Karnak Temple', 'Hot air balloons', 'Nile cruise'],
    imageUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800',
    latitude: 25.6872,
    longitude: 32.6396,
  },
  {
    id: 'hurghada',
    city: 'Hurghada',
    country: 'Egypt',
    airportCode: 'HRG',
    region: 'africa',
    vibes: ['beach', 'adventure', 'relaxation'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    averageCost: 1500,
    highlights: ['Red Sea diving', 'Beaches', 'Resorts', 'Desert trips'],
    imageUrl: 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800',
    latitude: 27.2579,
    longitude: 33.8116,
  },
  {
    id: 'rwanda',
    city: 'Kigali',
    country: 'Rwanda',
    airportCode: 'KGL',
    region: 'africa',
    vibes: ['adventure', 'nature', 'culture'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    averageCost: 5000,
    highlights: ['Gorilla trekking', 'Genocide Memorial', 'Cleanest city', 'Coffee'],
    imageUrl: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800',
    latitude: -1.9403,
    longitude: 29.8739,
  },
  {
    id: 'uganda',
    city: 'Kampala',
    country: 'Uganda',
    airportCode: 'EBB',
    region: 'africa',
    vibes: ['adventure', 'nature'],
    bestMonths: [6, 7, 8, 9, 12, 1, 2],
    averageCost: 4500,
    highlights: ['Gorilla trekking', 'Nile source', 'Safari', 'Chimpanzees'],
    imageUrl: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800',
    latitude: 0.3476,
    longitude: 32.5825,
  },
  {
    id: 'namibia',
    city: 'Windhoek',
    country: 'Namibia',
    airportCode: 'WDH',
    region: 'africa',
    vibes: ['adventure', 'nature'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 4000,
    highlights: ['Sossusvlei', 'Etosha', 'Skeleton Coast', 'Stargazing'],
    imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=800',
    latitude: -22.5609,
    longitude: 17.0658,
  },
  {
    id: 'botswana',
    city: 'Maun',
    country: 'Botswana',
    airportCode: 'MUB',
    region: 'africa',
    vibes: ['adventure', 'nature', 'luxury'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 6000,
    highlights: ['Okavango Delta', 'Safari', 'Chobe', 'Wildlife'],
    imageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    latitude: -19.9926,
    longitude: 23.4162,
  },
  {
    id: 'tunis',
    city: 'Tunis',
    country: 'Tunisia',
    airportCode: 'TUN',
    region: 'africa',
    vibes: ['history', 'culture', 'beach'],
    bestMonths: [4, 5, 6, 9, 10],
    averageCost: 1500,
    highlights: ['Medina', 'Carthage', 'Sidi Bou Said', 'Sahara'],
    imageUrl: 'https://images.unsplash.com/photo-1585904306392-ed18cbc52e67?w=800',
    latitude: 36.8065,
    longitude: 10.1815,
  },
  {
    id: 'addis-ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    airportCode: 'ADD',
    region: 'africa',
    vibes: ['culture', 'history', 'food'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 2000,
    highlights: ['Coffee birthplace', 'Lucy', 'Ethiopian cuisine', 'Churches'],
    imageUrl: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800',
    latitude: 8.9806,
    longitude: 38.7578,
  },
  {
    id: 'ghana',
    city: 'Accra',
    country: 'Ghana',
    airportCode: 'ACC',
    region: 'africa',
    vibes: ['culture', 'history', 'beach'],
    bestMonths: [11, 12, 1, 2],
    averageCost: 2000,
    highlights: ['Slave castles', 'Kakum', 'Markets', 'Afro culture'],
    imageUrl: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800',
    latitude: 5.6037,
    longitude: -0.1870,
  },
  {
    id: 'senegal',
    city: 'Dakar',
    country: 'Senegal',
    airportCode: 'DSS',
    region: 'africa',
    vibes: ['culture', 'beach', 'history'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    averageCost: 2000,
    highlights: ['Goree Island', 'Pink Lake', 'Music scene', 'Surfing'],
    imageUrl: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800',
    latitude: 14.7167,
    longitude: -17.4677,
  },
  {
    id: 'reunion',
    city: 'Saint-Denis',
    country: 'Reunion',
    airportCode: 'RUN',
    region: 'africa',
    vibes: ['nature', 'adventure', 'beach'],
    bestMonths: [5, 6, 7, 8, 9, 10, 11],
    averageCost: 3000,
    highlights: ['Piton de la Fournaise', 'Hiking', 'Creole culture', 'Beaches'],
    imageUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800',
    latitude: -21.1151,
    longitude: 55.5364,
  },

  // ============================================
  // OCEANIA (~20 destinations)
  // ============================================
  {
    id: 'sydney',
    city: 'Sydney',
    country: 'Australia',
    airportCode: 'SYD',
    region: 'oceania',
    vibes: ['city', 'beach', 'culture', 'food', 'nature'],
    bestMonths: [9, 10, 11, 12, 1, 2, 3],
    averageCost: 5000,
    highlights: ['Opera House', 'Harbour Bridge', 'Bondi Beach', 'Blue Mountains'],
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
    latitude: -33.8688,
    longitude: 151.2093,
  },
  {
    id: 'new-zealand',
    city: 'Queenstown',
    country: 'New Zealand',
    airportCode: 'ZQN',
    region: 'oceania',
    vibes: ['adventure', 'nature', 'relaxation'],
    bestMonths: [11, 12, 1, 2, 3],
    averageCost: 4500,
    highlights: ['Bungee jumping', 'Milford Sound', 'Lord of the Rings', 'Glaciers'],
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    latitude: -45.0312,
    longitude: 168.6626,
  },
  {
    id: 'fiji',
    city: 'Nadi',
    country: 'Fiji',
    airportCode: 'NAN',
    region: 'oceania',
    vibes: ['beach', 'relaxation', 'romance', 'family', 'adventure'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 4000,
    highlights: ['Island resorts', 'Snorkeling', 'Village visits', 'Water sports'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: -17.7765,
    longitude: 177.4356,
  },
  {
    id: 'tahiti',
    city: 'Papeete',
    country: 'French Polynesia',
    airportCode: 'PPT',
    region: 'oceania',
    vibes: ['beach', 'romance', 'luxury', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 8000,
    highlights: ['Bora Bora', 'Overwater bungalows', 'Diving', 'Lagoons'],
    imageUrl: 'https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=800',
    latitude: -17.6509,
    longitude: -149.4260,
  },
  {
    id: 'bora-bora',
    city: 'Bora Bora',
    country: 'French Polynesia',
    airportCode: 'BOB',
    region: 'oceania',
    vibes: ['romance', 'luxury', 'beach', 'relaxation'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 10000,
    highlights: ['Overwater bungalows', 'Mount Otemanu', 'Lagoon', 'Snorkeling'],
    imageUrl: 'https://images.unsplash.com/photo-1589179899221-94e1c4c10f5f?w=800',
    latitude: -16.5004,
    longitude: -151.7415,
  },
  {
    id: 'melbourne',
    city: 'Melbourne',
    country: 'Australia',
    airportCode: 'MEL',
    region: 'oceania',
    vibes: ['city', 'culture', 'food', 'nature'],
    bestMonths: [10, 11, 12, 1, 2, 3],
    averageCost: 4500,
    highlights: ['Laneways', 'Coffee culture', 'Great Ocean Road', 'Arts scene'],
    imageUrl: 'https://images.unsplash.com/photo-1514395462725-fb4566210144?w=800',
    latitude: -37.8136,
    longitude: 144.9631,
  },
  {
    id: 'great-barrier-reef',
    city: 'Cairns',
    country: 'Australia',
    airportCode: 'CNS',
    region: 'oceania',
    vibes: ['nature', 'adventure', 'beach', 'family'],
    bestMonths: [6, 7, 8, 9, 10],
    averageCost: 4000,
    highlights: ['Great Barrier Reef', 'Daintree', 'Snorkeling', 'Rainforest'],
    imageUrl: 'https://images.unsplash.com/photo-1523437113738-bbd3cc89fb19?w=800',
    latitude: -16.9186,
    longitude: 145.7781,
  },
  {
    id: 'perth',
    city: 'Perth',
    country: 'Australia',
    airportCode: 'PER',
    region: 'oceania',
    vibes: ['beach', 'city', 'nature', 'relaxation'],
    bestMonths: [10, 11, 3, 4, 5],
    averageCost: 4000,
    highlights: ['Rottnest Island', 'Beaches', 'Wine regions', 'Quokkas'],
    imageUrl: 'https://images.unsplash.com/photo-1573167243872-43c6433b9d40?w=800',
    latitude: -31.9505,
    longitude: 115.8605,
  },
  {
    id: 'gold-coast',
    city: 'Gold Coast',
    country: 'Australia',
    airportCode: 'OOL',
    region: 'oceania',
    vibes: ['beach', 'family', 'nightlife', 'adventure'],
    bestMonths: [4, 5, 9, 10, 11],
    averageCost: 3500,
    highlights: ['Surfing', 'Theme parks', 'Hinterland', 'Beaches'],
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
    latitude: -28.0167,
    longitude: 153.4000,
  },
  {
    id: 'tasmania',
    city: 'Hobart',
    country: 'Australia',
    airportCode: 'HBA',
    region: 'oceania',
    vibes: ['nature', 'food', 'adventure', 'culture'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 3500,
    highlights: ['MONA', 'Cradle Mountain', 'Wilderness', 'Fresh produce'],
    imageUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
    latitude: -42.8821,
    longitude: 147.3272,
  },
  {
    id: 'auckland',
    city: 'Auckland',
    country: 'New Zealand',
    airportCode: 'AKL',
    region: 'oceania',
    vibes: ['city', 'nature', 'adventure', 'food'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 4000,
    highlights: ['Sky Tower', 'Waiheke Island', 'Volcanoes', 'Harbour'],
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    latitude: -36.8509,
    longitude: 174.7645,
  },
  {
    id: 'rotorua',
    city: 'Rotorua',
    country: 'New Zealand',
    airportCode: 'ROT',
    region: 'oceania',
    vibes: ['nature', 'culture', 'adventure', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 3000,
    highlights: ['Geothermal', 'Maori culture', 'Hot springs', 'Redwoods'],
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    latitude: -38.1368,
    longitude: 176.2497,
  },
  {
    id: 'wellington',
    city: 'Wellington',
    country: 'New Zealand',
    airportCode: 'WLG',
    region: 'oceania',
    vibes: ['city', 'culture', 'food', 'nature'],
    bestMonths: [12, 1, 2, 3],
    averageCost: 3500,
    highlights: ['Te Papa', 'Cable car', 'Craft beer', 'Film scene'],
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    latitude: -41.2865,
    longitude: 174.7762,
  },
  {
    id: 'milford-sound',
    city: 'Milford Sound',
    country: 'New Zealand',
    airportCode: 'ZQN',
    region: 'oceania',
    vibes: ['nature', 'adventure'],
    bestMonths: [12, 1, 2, 3, 4],
    averageCost: 4500,
    highlights: ['Fjord cruises', 'Waterfalls', 'Wildlife', 'Hiking'],
    imageUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800',
    latitude: -44.6414,
    longitude: 167.8997,
  },
  {
    id: 'cook-islands',
    city: 'Rarotonga',
    country: 'Cook Islands',
    airportCode: 'RAR',
    region: 'oceania',
    vibes: ['beach', 'relaxation', 'romance', 'nature'],
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    averageCost: 4500,
    highlights: ['Lagoon', 'Aitutaki', 'Polynesian culture', 'Snorkeling'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: -21.2075,
    longitude: -159.7764,
  },
  {
    id: 'samoa',
    city: 'Apia',
    country: 'Samoa',
    airportCode: 'APW',
    region: 'oceania',
    vibes: ['beach', 'culture', 'relaxation', 'nature'],
    bestMonths: [5, 6, 7, 8, 9, 10],
    averageCost: 3500,
    highlights: ['To Sua Ocean Trench', 'Beaches', 'Fa\'a Samoa culture', 'Waterfalls'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: -13.8333,
    longitude: -171.7500,
  },
  {
    id: 'vanuatu',
    city: 'Port Vila',
    country: 'Vanuatu',
    airportCode: 'VLI',
    region: 'oceania',
    vibes: ['beach', 'adventure', 'nature', 'culture'],
    bestMonths: [4, 5, 6, 7, 8, 9, 10],
    averageCost: 3500,
    highlights: ['Blue lagoons', 'Volcanoes', 'Diving', 'Tribal culture'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: -17.7334,
    longitude: 168.3273,
  },
  {
    id: 'new-caledonia',
    city: 'Noumea',
    country: 'New Caledonia',
    airportCode: 'NOU',
    region: 'oceania',
    vibes: ['beach', 'culture', 'nature', 'relaxation'],
    bestMonths: [4, 5, 9, 10, 11],
    averageCost: 4000,
    highlights: ['Lagoon', 'French culture', 'Isle of Pines', 'Diving'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: -22.2758,
    longitude: 166.4580,
  },
  {
    id: 'palau',
    city: 'Koror',
    country: 'Palau',
    airportCode: 'ROR',
    region: 'oceania',
    vibes: ['adventure', 'beach', 'nature', 'adventure'],
    bestMonths: [11, 12, 1, 2, 3, 4],
    averageCost: 5000,
    highlights: ['Jellyfish Lake', 'Rock Islands', 'World-class diving', 'Marine life'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: 7.5150,
    longitude: 134.5825,
  },
  {
    id: 'guam',
    city: 'Tamuning',
    country: 'Guam',
    airportCode: 'GUM',
    region: 'oceania',
    vibes: ['beach', 'family', 'history', 'relaxation'],
    bestMonths: [12, 1, 2, 3, 4, 5],
    averageCost: 3500,
    highlights: ['Tumon Bay', 'WWII history', 'Duty-free shopping', 'Chamorro culture'],
    imageUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800',
    latitude: 13.4443,
    longitude: 144.7937,
  },
];

// Helper functions
export function getDestinationById(id: string): Destination | undefined {
  return DESTINATIONS.find(d => d.id === id);
}

export function getDestinationsByRegion(region: string): Destination[] {
  return DESTINATIONS.filter(d => d.region === region);
}

export function getDestinationsByVibe(vibe: DestinationVibe): Destination[] {
  return DESTINATIONS.filter(d => d.vibes.includes(vibe));
}

export function getDestinationsForMonth(month: number): Destination[] {
  return DESTINATIONS.filter(d => d.bestMonths.includes(month));
}

export function searchDestinations(query: string): Destination[] {
  const lowerQuery = query.toLowerCase();
  return DESTINATIONS.filter(
    d =>
      d.city.toLowerCase().includes(lowerQuery) ||
      d.country.toLowerCase().includes(lowerQuery) ||
      d.airportCode.toLowerCase().includes(lowerQuery) ||
      d.vibes.some(v => v.includes(lowerQuery))
  );
}
