'use client';

import { Button } from '@/components/ui';
import type { Itinerary } from '@/types/itinerary';

interface ItineraryExportProps {
  itinerary: Itinerary;
}

export function ItineraryExport({ itinerary }: ItineraryExportProps) {
  const exportAsText = () => {
    let text = `${itinerary.destination} Trip Itinerary\n`;
    text += `${'='.repeat(50)}\n\n`;
    text += `Dates: ${itinerary.dates.start} - ${itinerary.dates.end}\n`;
    text += `Hotel: ${itinerary.hotel.name}\n`;
    text += `Location: ${itinerary.hotel.neighborhood}\n\n`;

    itinerary.days.forEach((day) => {
      text += `${'━'.repeat(50)}\n`;
      text += `DAY ${day.dayNumber} (${day.dayOfWeek}) — ${day.theme}\n`;
      text += `${'━'.repeat(50)}\n\n`;

      day.items.forEach((item) => {
        const checkbox = item.completed ? '[x]' : '[ ]';
        text += `${checkbox} ${item.time.padEnd(10)} ${item.activity}\n`;
        text += `${''.padStart(14)}📍 ${item.location} • ${item.duration}\n`;
        if (item.notes) {
          text += `${''.padStart(14)}💡 ${item.notes}\n`;
        }
        if (item.costEstimate) {
          text += `${''.padStart(14)}💰 ${item.costEstimate}\n`;
        }
        text += '\n';
      });
    });

    if (itinerary.packingTips.length > 0) {
      text += `\n${'━'.repeat(50)}\n`;
      text += `PACKING TIPS\n`;
      text += `${'━'.repeat(50)}\n\n`;
      itinerary.packingTips.forEach((tip) => {
        text += `• ${tip}\n`;
      });
    }

    if (itinerary.localTips.length > 0) {
      text += `\n${'━'.repeat(50)}\n`;
      text += `LOCAL TIPS\n`;
      text += `${'━'.repeat(50)}\n\n`;
      itinerary.localTips.forEach((tip) => {
        text += `• ${tip}\n`;
      });
    }

    text += `\n${'━'.repeat(50)}\n`;
    text += `EMERGENCY INFO\n`;
    text += `${'━'.repeat(50)}\n\n`;
    text += `📞 ${itinerary.emergencyInfo.emergencyNumber}\n`;
    if (itinerary.emergencyInfo.embassy) {
      text += `🏛️ ${itinerary.emergencyInfo.embassy}\n`;
    }
    if (itinerary.emergencyInfo.hospitalNearby) {
      text += `🏥 ${itinerary.emergencyInfo.hospitalNearby}\n`;
    }

    text += `\n\nGenerated by HonestNomad\n`;

    // Download
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${itinerary.destination.toLowerCase().replace(/\s+/g, '-')}-itinerary.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const printItinerary = () => {
    window.print();
  };

  return (
    <div className="flex gap-2">
      <Button
        variant="secondary"
        size="sm"
        onClick={exportAsText}
        className="bg-white/20 border-white/30 text-white hover:bg-white/30"
      >
        Export
      </Button>
      <Button
        variant="secondary"
        size="sm"
        onClick={printItinerary}
        className="bg-white/20 border-white/30 text-white hover:bg-white/30 no-print"
      >
        Print
      </Button>
    </div>
  );
}
